### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by GjjvdBurg** [bepaald/signalbackup-tools#10]
This is not an issue, I just wanted to quickly say thank you for making this tool! 

Using this I was able to make a [little script](https://github.com/GjjvdBurg/signal2html) to convert my signal backups to nice HTML. This wouldn't have been feasible without all the work you've done to deal with the backup files, so thank you very much! :)

**Comment by bepaald** [comment]
Cool!

When I first started to work with backups, Signal didn't have the current backup functionality, only a (unencrypted) xml backup which I also converted to html (though not as good-looking as yours). When the new backups were introduced, my first goal with this program was actually to just replicate the same behavior of exporting to html (only with media included, as attachments were not present in signal's original xml backups). However, I got sidetracked by all the other functions the program now has, though html export is still on the to do list (see [https://github.com/bepaald/signalbackup-tools#future-plans](https://github.com/bepaald/signalbackup-tools#future-plans)).

I don't know if you'll inspire me to actually make some work of it, or make me delay it even longer since you already solved it! Haha. Anyway, it's a cool script, I'll defenitely play around with it this weekend! And thank you for your kind words!
