### ISSUE TITLE
Allow --croptothreads and --importthreads to match thread titles as alternative to IDs

### ISSUE THREAD

**Issue by Meteor0id** [bepaald/signalbackup-tools#109]
Try to match thread names (or phone number) as alternative to thread ID. Obviously this could fail if there are multiple treads with the same name, but that's ok, just throw a warning "failed to match thread xyz, try matching by phone number or thread id"

**Comment by bepaald** [comment]
Yeah, sure, this sounds ok. But it'll may be a little while before I get around to it.

**Comment by bepaald** [comment]
I think this is done. It has one small negative side effect: since any string of characters can now refer to an existing thread (not just numbers and ranges), the program will only come up with an error after opening the database and determining the named thread does not exist. Also, the parameter list is now (or can be) ambiguous: multiple contacts can have the same name (this causes failure) and contacts can have simple numeric names (which is always interpreted as thread._id as it used to).

**Comment by Meteor0id** [comment]
You could of course add '--croptothreadbynane' to solve the numeric name issue.
And when multiple contacts have the same name throw a warning and continue to export both. The warning can include a list of threads and their numbers.

**Comment by bepaald** [comment]
Yes, I think I might do that instead. Should be a small thing to implement now, probably tomorrow or this weekend.

**Comment by bepaald** [comment]
It was such a small change, I did it quickly just now. All the options mentioned above have a `--[option]byname` counterpart.
