### ISSUE TITLE
html export of call log (call-log.html)

### ISSUE THREAD

**Issue by Meteor0id** [bepaald/signalbackup-tools#111]
Signal added an overview of all calls. Shouldn't be too hard to render a similar overview as an html export.
Idea for a future enhancement

**Comment by bepaald** [comment]
This feature can be tested by adding the `--includecalllog` switch when exporting html. To do:
- Document it (readme and `--help`)
- Add media print css (could probably mostly be copied from the index html)

There are a few enumerators in the call table, but I do not have all of them in my backups at this moment (what even _is_ an 'ad-hoc call'?), so it is possible icons/text are missing or wrong for some combinations of them. (ref: https://github.com/bepaald/signalbackup-tools/blob/0a2d3ac10f1628e452ac29869cfc190c22eb48e6/signalbackup/htmlwritecalllog.cc#L77-L93)

**Comment by bepaald** [comment]
I believe this is done. The logic behind the different icons for the call-types and -events was quite strange, but I ended up finding it in the Signal source code and re-implementing the same logic. So that should be done. I also added media-print css (mostly copied from the index.html + the same trick for icons as used in the main message pages) and updated the readme and `--help`-output. 

I'm just considering making this option default to true, instead of false. But I'm still thinking that over and that's not really part of this issue i think. Let me know if anything appears not to work correctly.
