### ISSUE TITLE
render html overview of group members and settings

### ISSUE THREAD

**Issue by Meteor0id** [bepaald/signalbackup-tools#112]
Idea for a future enhancement, actually seeing who are in a group is useful information

**Comment by bepaald** [comment]
I just quickly added the list of members to group chats. It shouldn't be too difficult to add other information there as well (what did you have in mind?).

**Comment by Meteor0id** [comment]
For reference, Bepaald and I are also discussing this as part of #104

> Other group data to show would be:
>
>    Is this group muted (this should actually also be shown for one-on-one conversations!)
>    current disappearing message timer on or off and if on how long (this should actually also be shown for one-on-one conversations!)
>    group link on or off and if on what is the link
>    Are there any pending join requests? if so who.
>    Are there any pending invites? if so who.
>    Who may add new members
>    who may edit the group info
>    who may send messages and start calls in this group
>    the group description!

**Comment by bepaald** [comment]
I hope I have some time for this tomorrow as well

**Comment by Meteor0id** [comment]
I think all of this looks alright. Not sure if you need a distinction between "invited by you" and "invited by others" or show who made it invite, I haven't got those in my test cases at this time.

**Comment by Meteor0id** [comment]
I guess a change you could consider is to list members with their profile details (picture maybe more)

**Comment by Meteor0id** [comment]
tiny css enhancements:

`<div class="pack-status">Available</div>`
does not have flex-basis: 100% so it can end up inline with the previous sticker

and it might make sense to start counting at 1 rather than 0 when numbering stickers. That way it's obvious how many stickers there are when looking at the last sticker; it avoids confusion. In coding it can make sense to start at 0, but humans typically start with 1 when counting items.

**Comment by bepaald** [comment]
>tiny css enhancements:
>
><div class="pack-status">Available</div>
>does not have flex-basis: 100% so it can end up inline with the previous sticker

Sure. I don't really see any difference, under what circumstances do you see a problem? I tried resizing the window, but don't see any difference with any size. I'm fine adding it anyway (already done locally even).

>and it might make sense to start counting at 1 rather than 0 when numbering stickers. That way it's obvious how many stickers there are when looking at the last sticker; it avoids confusion. In coding it can make sense to start at 0, but humans typically start with 1 when counting items.

The numbers are actually like that because they're the internal `id`s of the stickers in the pack. If you were to inspect the stickers in the backup, or references to those stickers in the database, that number is how you match them to a specific sticker in each pack. In fact, the only reason they appear in order in the HTML is because I'm explicitly sorting them that way in the code. I should probably make it more clear somehow that this is the `id`, but I'm not sure how.

I could add a title to each value, something like so:
![Screenshot 2024-05-30 at 21-28-22 Signal stickerpacks](https://github.com/bepaald/signalbackup-tools/assets/38437099/61da4887-7e3f-4b65-99c1-6931cb22de6e)

But I'd really rather not put the `id` and the emoji on separate lines, because I think it looks ugly. Alternatively, I could just not show the `id` at all and use a (otherwise meaningless) sequential number (starting at 1), or just not number the stickers at all. What do you think?

**Comment by Meteor0id** [comment]
not sure why the "pack status" element was inline for me but not for you but flex-basis 100 will fix it so it doesnt matter why.

Ah fair point with the id's, numbering starting with 1 might in that case actually cause mistakes when coding. So maybe just leave them as they were starting at 0. And who really cares anyway now that I think it through.

**Comment by bepaald** [comment]
>not sure why the "pack status" element was inline for me but not for you but flex-basis 100 will fix it so it doesnt matter why.

Sorry, I noticed it now, I was only looking at the other "pack status" element (the 'installed' one). Either way, it's fixed now. Thanks!

>Ah fair point with the id's, numbering starting with 1 might in that case actually cause mistakes when coding. So maybe just leave them as they were starting at 0. And who really cares anyway now that I think it through.

Yeah, ok I'll leave it like it is. Thanks!

**Comment by bepaald** [comment]
Looking at this thread, the last bit that seems left was:

>I guess a change you could consider is to list members with their profile details (picture maybe more)
And add "Mute notifications", "Mentions" and "Custom notifications"

I had a look at this. I don't think I'll be adding all members' info on the group page, that seems like a lot of clutter (and work). Also I suppose there is now the "all known contacts" page for that.

I've added the "Mentions" settings and whether "Custom notifcations" are enabled or not. I did implement actually showing the custom notifications as well, but it looks ugly and of little use so I'm thinking of removing it (just showing "Enabled"/"Disabled"). What do you think:
![Screenshot 2024-05-31 at 20-32-57 custom notifications](https://github.com/bepaald/signalbackup-tools/assets/38437099/c6fbc15a-9e98-4e05-aced-4a45b820e17b)

Lastly the "Mute notifications". This one is tricky: there is only a timestamp `mute_until` in the database, but since the backup file itself has no timestamp and there is now way to know _when_ the muting was enabled, there is no way to know if the thread was muted for 1 hour or 8 hours or a week. Also, the `mute_until` column is not reset (at least not necessarily) when the time has expired. I have conversations in my backup with a `mute_until` value sometime in 2022.

What I'm thinking is to only show "Muted: no/yes" if the conversation mute-state is certain. That is, `mute_until` = 0 (not muted) or `mute_until` is set to maximum value for a signed 64 bit number (which is when the mute is set to "Always", this corresponds to the date 17 Aug 29227894). But if `mute_until` is any other value, I'll just not add this line at all as to not imply anything that may be not be true.

Thoughts?

**Comment by Meteor0id** [comment]
It can be relevant to know if a call ringtone was "none (disabled)" or "enabled" but which ringtone it is is irrelevant in my view. Just not sure if you can identify a ringtone "none" with certainty.

About mute until:
Don't omit the line when uncertain but state "mute state: could not be determined"

I'm approaching html export from the viewpoint of forensic evidence so that's why stating uncertainty is also important. If you include "could not be determined" at least one can't say "if it was muted the export would have said muted".

**Comment by bepaald** [comment]
I think this is done.

>It can be relevant to know if a call ringtone was "none (disabled)" or "enabled" but which ringtone it is is irrelevant in my view. Just not sure if you can identify a ringtone "none" with certainty.

As far as I can tell, ringtones aren't "enabled" or "disabled" ever. The field is either some (meaningless) string linking to an unknown local sound file (as in the above screenshot), or it is empty which means "use the global default ringtone". I think a "disabled" ringtone is accomplished by muting the thread.

In regards to the mute-state, I went with your suggestion.

So I think that should take care of everything in this issue. Any last remarks? Can this one maybe be closed?
