### ISSUE TITLE
Do not insist on END frame

### ISSUE THREAD

**Issue by tadu** [bepaald/signalbackup-tools#12]
I happen to have had a backup that missed the last 8k (due to the first 8k being duplicated during transmit). That basically means no END frame, causing the backup read to fail. However, I'd still like to keep whatever is there, so I made a tiny change in exporttodir.cc:

```
   std::cout << "Writing EndFrame..." << std::endl;
   if (!writeRawFrameDataToFile(directory + "/End.sbf", d_endframe))
-    return false;
+    ;
```
 

...which essentially doesn't exit if the end frame couldn't be written (due to not having been read before). That allowed me to copy the regular end frame (which does not contain any information...), and thus keep as much as possible from my backup.

I'm sure you know your code better to find a more suitable way to fix this, but this is what saved my day.

**Comment by bepaald** [comment]
Ok, agreed. The reason it was an error was that a truncated input backup file would lead to an invalid output backup file in most cases (ie one that cannot be imported by the app). But your case is definitely a valid use-case.

I already had a function to deal with (heavily) truncated files, though that function is currently most likely broken it naturally needed to add a new EndFrame also. I now just issue a warning when the endframe was not found during reading the input and than generate one, so that it is always present when writing output. That should fix it.

Let me know if there's problems with this. Thanks!
