### ISSUE TITLE
--exporttxt missing media

### ISSUE THREAD

**Issue by MrTuffGong** [bepaald/signalbackup-tools#155]
Hi,

if I export the backup into txt files instead of getting [2023-07-10 01:26] *** <bob> sent "Signal-1.jpeg" I am only getting [Sep 02, 2020 22:42:05] *** <bob> sent file of type image/jpeg

So there is no way of knowing which media file has to be placed here. Anyone had the same issue and has a fix for it?

**Comment by bepaald** [comment]
This is expected behavior for attachments that do not have a file name. Also, quite explicitly, `--exporttxt` does not export media, so there is nothing to correlate.

What are you trying to match the filenames with? If you export the attachments using the `--dumpmedia` option, you can easily match the files by date `Sep 02, 2020 22:42:05` -> "2020-09-02-224205.jpg".

**Comment by bepaald** [comment]
I assume your question was answered. Feel free to open a new issue if there's anything else. Thanks!
