### ISSUE TITLE
Option to log stuff

### ISSUE THREAD

**Issue by Klimmbimmel** [bepaald/signalbackup-tools#164]
I know, it is a typically design of shell programs of Unix-like software, to always print to standard output, but this is complemented with an ease of use to put output into a file (_xyz > file.log_).

This is different(?) on windows, so at least there, the output should be automatically logged, especially for those commands, which take a lot of time like merging or alike... Also I don't see an option to log output, that would also be a start :)

**Comment by bepaald** [comment]
Yeah, this has been requested before, and I always meant to do it. It's just a lot of work for little gains. But I already had a Logger class in another project, so I've finally started integrating that into this project as well.

It will be a while (maybe a long while) before this is finished, I first need to switch all existing `std::cout`s to the new Logger option. When that is finished I'll enable the file-output and report back here. In the meantime, `> file.log` is still the way to go.

>This is different(?) on windows,

The question mark is pretty interesting, have you actually tried? Because I'm not a big Windows user, but the last time I tried, redirecting output `>` worked exactly the same as on Linux.

**Comment by bepaald** [comment]
This should be finished now. It's a bit messy, but that is because output was messy before, and due to the amount of work I (mostly) just did a straight port to the new Logger class.

There should be no raw `cout`'s in the project anymore (except commented out, or in the Logger class). The logger has an option to copy it's output to file. Use `-l/--logfile <output.log>` to write to 'output.log' while running.

If you see any problems with this, or have any other feedback, please let me know here (or open a new issue if you want).

Thanks for reporting!
