### ISSUE TITLE
wrong passphrase or unkown data corruption type?

### ISSUE THREAD

**Issue by lo-zed** [bepaald/signalbackup-tools#166]
Hi
first of all, thank you very much for your work.
I had carefully written down my passphrase and when I wanted to restore it, it miserably failed. So I'd like to ask you your opinion.

I installed the tool through archlinux AUR, here's the log:

```
signalbackup-tools (signalbackup-tools) source version 20231205.205546
BACKUPFILE VERSION: 1
BACKUPFILE SIZE: 377480320
COUNTER: 1289993949
Reading backup file...
FRAME 0 (000.0%)...
Error: Failed to read next frame (4052196911 bytes at filepos 60)
 *** NOTE : IT IS LIKELY AN INCORRECT PASSPHRASE WAS PROVIDED ***
Warning: EndFrame was not read: backup is probably incomplete
Database version: 4294967295

Exporting backup to '/tmp/rawbackup/new.backup'
Writing HeaderFrame...
Writing DatabaseVersionFrame...
Error: DataBaseVersionFrame not found
```

So it seems the passphrase is wrong?! I don't understand how that can be since I never disabled/re-enabled backups. But anyway it is what it is.

I read that it is unfeasible to try to hack the passphrase. But can you think of any further steps before I abandon? another type of backup corruption?

Thank you for your time

Edit: removed question about hacking the passphrase

**Comment by bepaald** [comment]
>So it seems the passphrase is wrong?! I don't understand how that can be since I never disabled/re-enabled backups. But anyway it is what it is.
>
>I read that it is unfeasible to try to hack the passphrase. But can you think of any further steps before I abandon? another type of backup corruption?

I am sorry to have to bring bad news. It is _extremely_ unlikely that there is data corruption, in these cases it is almost 100% certain that the passphrase was not correct. Though, technically, there is no way to distinguish the two cases. Either way, I'm afraid you're out of luck: as you already realize brute forcing the passphrase is not doable, and recovering from data corruption (like this tool used to do) is not possible anymore since `BACKUPFILE VERSION: 1`.

So unfortunately, I wouldn't know what you could possibly do at this point. In the past I've recommended people (who were convinced they had the correct passphrase) to try every other passphrase they had written down. This actually turns out to be the solution quite often. But other than that there is nothing I can think of. Sorry.

**Comment by lo-zed** [comment]
Thank you for your quick reply. I've found an older backup with `BACKUPFILE VERSION: 0`. It is now trying to recover. But I guess, if that fails, that doesn't help me much, right?

**Comment by bepaald** [comment]
>Thank you for your quick reply. I've found an older backup with BACKUPFILE VERSION: 0. It is now trying to recover. But I guess, if that fails, that doesn't help me much, right?

Indeed. Also, if the problem occurs in the same way (failure on the very first (encrypted) frame): it is still almost 100% certain the passphrase is incorrect. The recovery will not fix this, it will try to find an uncorrupted frame later in the file by decrypting it, and checking the data integrity and the contents of the frame, but always with the passphrase provided. I'd say at best you'll get a few false positives.

While this decryption failure on the first frame already means an incorrect passphrase, the chances of having two different backups both be corrupted at the same position in the file are astronomically small. Unless you can somehow find the correct passphrase, you might want to mentally prepare for the contents of these backups being lost forever.

**Comment by studiok87** [comment]
Thank you for your tool, @bepaald 

I have a similar problem, didn't want to open a new issue. I did a reset and firmware upgrade of my phone and suddenly I can't restore any of my backups. I have 8 different backups from the last two years, stored on different harddisks, and for each of those Signal says that the passphrase is wrong. But I'm absolutely sure on the passphrase, there's only this one and this worked with some of the backups in the past (resetting my phone everytime before installing new firmware via adb). 

When I skip the restore in Signal and verify the passphrase, the app says it's the right one, all with Screenshots here: https://github.com/signalapp/Signal-Android/issues/13333
Tried it now on 3 different phones and Android 11/Lineage as well as Android 12, 13 and 14 and with two older Signal versions from apkmirror.

With some older backups, Signal Backup Tools starts bruteforcing and checking offset, it ran for 3 days and nights nonstop and checked about 15% of the filesize, so I stopped it. Is that normal, shall I run it again until it's finished?
Thank you!

First Log is with newest backup-file, results are the same when I enter any random passphrase, second with older backup when it starts checking offsets.

```
signalbackup-tools_win.exe signal-[DATE].backup2 [passphrase] --output NEWBACKUPFILE
 *** Starting log:   ***
signalbackup-tools (signalbackup-tools_win.exe) source version 20240110.092132 (Win)
BACKUPFILE VERSION: 1
BACKUPFILE SIZE: 11070202889
COUNTER: 411937970
Reading backup file...
FRAME 0 (000.0%)...
[Error]: Failed to read next frame (1509594122 bytes at filepos 60)
 *** NOTE : IT IS LIKELY AN INCORRECT PASSPHRASE WAS PROVIDED ***
[Warning]: EndFrame was not read: backup is probably incomplete
Database version: 4294967295

Exporting backup to 'NEWBACKUPFILE'
Writing HeaderFrame...
Writing DatabaseVersionFrame...
[Error]: DataBaseVersionFrame not found
[Error]: Failed to export backup to 'NEWBACKUPFILE'

---------------------------------------------------------------------------------------------------------------

signalbackup-tools_win.exe signal-[OLDER_DATE].backup [passphrase] --output NEWBACKUPFILE
 *** Starting log:   ***
signalbackup-tools (signalbackup-tools_win.exe) source version 20240110.092132 (Win)
BACKUPFILE VERSION: 0
BACKUPFILE SIZE: 9169783932
COUNTER: 2960981762
Reading backup file...
FRAME 0 (000.0%)...


[Warning]: Bad MAC in frame: theirMac: (hex:) 69 4c 57 21 c2 c0 35 b5 3b 80
                              ourMac: (hex:) 1d 9c 09 89 22 ad 49 4e 3e 7c fa 4c 67 96 34 c1 03 ef 49 c8 eb f2 14 0e 85 22 69 49 57 8b b4 24
 *** NOTE : IT IS LIKELY AN INCORRECT PASSPHRASE WAS PROVIDED ***
[Error]: Failed to get valid frame from decoded data...
         Encrypted data had failed verification (Bad MAC)
Starting bruteforcing offset to next valid frame... starting after: 58
Checking offset 13973150 bytes
```

**Comment by bepaald** [comment]
Well, that does not look good.

I must say that everything about this just screams incorrect passphrase:
- Obviously, resetting your phone, or doing whatever with you phone, does not affect any of the 8 backups living on your computer somewhere.
- All 8 of them, on different harddisks, surely have not corrupted simultaneously (and at the same file position: 0!).
- Lastly, a bug was introduced in both Signal and this program, which use different crypto-libraries in different programming languages and nobody else is running into the same bug. (Also, at least for `BACKUPFILE VERSION 0`, the decryption code has not been significantly touched in years)

The only thing I can think of is incorrect passphrase. If you have _any_ old, outdated passphrases lying around, I implore you to try all of them on all those backups.

> But I'm absolutely sure on the passphrase, there's only this one and this worked with some of the backups in the past

Did it work on _these_ specific backups? How sure are you of that? Maybe you (inadvertently) disabled and re-enabled backups at some point before the first of these 8 backups?

I'm not sure running the bruteforcing any longer will help you. The recovery mode will recover at some point _if there is recoverable data_, but it does not bruteforce the passphrase: it will always assume the user provided one is correct (obviously bruteforcing the passphrase itself is not feasible). The recovery mode is inherently slow, and can not be multithreaded (information of the previous frames is needed for decrypting the next). It is usually fairly fast only because the amount of corruption is a few KB, maybe an MB (a couple hd sectors or network packets). But when the program is just fed gigabytes of random bytes, you really notice that the recovery takes some time. 

I really hate giving you this news, but unless you find another passphrase, I'm not sure there is anything I can do for you. So sorry.

**Comment by studiok87** [comment]
Thank you very much for your answer, I'm 120% sure on the passphrase. And Signal verifies it as correct if I skip the restore-process, which it doesn't if I enter a random passphrase there.
Last firmware on my phone before updating was from May 2023, so I'm sure the backups (or at least one, the one that I restored then) worked it the past, I never dirty flashes on Android.
Maybe I disabled and re-enabled backups somehow but as a long-time Signal user and someone not into doing drugs, I'm quite sure I would remember this 😂
Anyway, thanks for your support, I give up now and will use your tool from now on for backups or maybe the fork of johanw666.

**Comment by bepaald** [comment]
>Thank you very much for your answer, I'm 120% sure on the passphrase. And Signal verifies it as correct if I skip the restore-process, which it doesn't if I enter a random passphrase there.
Last firmware on my phone before updating was from May 2023, so I'm sure the backups (or at least one, the one that I restored then) worked it the past, I never dirty flashes on Android.
Maybe I disabled and re-enabled backups somehow but as a long-time Signal user and someone not into doing drugs, I'm quite sure I would remember this 😂

Fair enough, maybe I was a bit firm on the wrong passphrase hypothesis. Though I honestly still don't see another option. I guess in the end it doesn't matter, the end result is the same. If you want another long shot (I personally wouldn't bother at this point, but that's just me), there is yet a 3rd implementation, using another language and cryptography library you could test with: https://github.com/DLu/SignalBackupParser. It is just a library though, so you'd need to write two or three lines of python to actually have it read your backup file.

I hope your bug report in Signal gets a response at some point, I'm curious if they have any theories about the successful verification.

Good luck to you, I hope you never run into anything like this again.
