### ISSUE TITLE
Question (issue?) regarding read/sent status after merging

### ISSUE THREAD

**Issue by hugogithubs** [bepaald/signalbackup-tools#174]
Hi,

Version: newest , but I think also older versions

I have two backup files:
1. from 2023-08, database version 201 (last complete backup)
2. actual from now,  database version 211 (I deleted some older attachements out of signal app)

Goal is to get a html export with all messages and attachments.
If I export both files separated the sent and read status of all messages in both htmlexports are ok.
If I crop-to date (to prevent dobled messages) new file and merge both (cropped and old) files all messages from older file are set to "sent" (nor delivered nor read). 
(for "upgrade" to version 211 reason, I merge the old one to the new one)

Is this an issue or intentional behaviour?
Or do I something wrong or do I expect something wrong?

**Comment by bepaald** [comment]
That is not intentional. Very curious, there were some changes to the way Signal stores the read status of messages, but I didn't think it had any effect on this program, maybe it did. 

Thanks for the detailed report, it shouldn't be too hard to reproduce this, so hopefully I can fix it easily. I may be a bit busy for a few days but I'll get to it as soon as I have a little time.

Thanks!

**Comment by bepaald** [comment]
Ok, so after investigating, while this case is not intentional, it is an expected result of merging 'incompatible' database versions. Between dbv 201 and 211 the `read_receipt_count` column was renamed to `has_read_receipt`.

In the early days this program used to just print an error and abort in this case, but later on, it would have just dropped the column in order to try to go ahead with the merge. (A message should have been printed during the merge stating _'NOTE: Dropping column read_receipt_count from source'_). This has meant that merging different database versions was possible even if columns were added or removed from the tables.

However, when a column was renamed instead of removed (such as in your case), it was dropped and its replacement would just be filled with the default value (in this case '0': not viewed/read/delivered).

I have now added a translation system for column names known to be equivalent. So, when the merge attempts to insert a non-existing column into a newer database, it now first checks if it goes by another name before dropping it.

I have not thoroughly tested this function, I'll leave that to you. Please update and try the same procedure again and let me know if it works.

Thanks!

**Comment by hugogithubs** [comment]
Hi,
I also saw this "note" in log.
However, since I don't have any in-depth knowledge of the structure of the underlying database, I assumed that it was "just" a "note" and that it would be okay and would handled in any way by your software ;-).

I will run same test again and will report you here.

**Comment by hugogithubs** [comment]
Version:
 20240103.164819 (Win)

Result:
**Regarding message `read status` test is ok.**

But:
I now took a closer look at the log regarding "notes" and found further entries, but I don't know whether they are really just informative or represent unhandled problems:

```
Importing statements from source table 'groups'...1 entries...
  NOTE: Dropping column 'groups.avatar_relay' from source : Column not present in target database
  ...
  NOTE: Dropping column 'groups.display_as_story' from source : Column not present in target database
  NOTE: Dropping column 'groups.auth_service_id' from source : Column not present in target database

```
Maybe it would be helpful for merging command if there would be a compatibility check or a new command for that before the start of the merge process to identify problems in advance? 
In the moment I have no deeper look into your code ... perhaps you already have this? 

Thanks a lot for your effort.

**Comment by bepaald** [comment]
Thanks that looks good!

The `Dropping column` messages really are fine. I'll add some more columns to the translation data, but some columns just simply don't exist anymore and _should_ be dropped. `groups.auth_service_id` for example: if the database not in a backup, but in a live, working Signal installation, it would also simply remove that column.

Really there is no way to be more accurate trying to determine compatibility. There are some database versions which are known to be incompatible, and the program checks for these before the merge process (here: https://github.com/bepaald/signalbackup-tools/blob/66e1475de7b758f542498783885cbcf0917b71f6/signalbackup/importthread.cc#L26-L36). Continuously checking compatibilty between new database versions would be a full time job (and a difficult one at that). Besides, the changing of version number directly indicates a change in database structure, so really the only way to merge backups (apart from how I'm doing it now) is to just enforce the database version to be equal. But that would greatly limit the usefulness of the function and be overly restricting since merging different version mostly works fine.

I'm pretty happy with the addition of the column-translation function (though it will also be a bit of work keeping it up-to-date), thanks to your report. So thank you!

I think this issue is solved?

**Comment by hugogithubs** [comment]
Hi,
thank you for clarification.
For the moment everything looks good 👍 .
From now on I will pay more attention to "notes" and version numbers to be on the safe side ;-) !

FMPV you can close.
Bye

**Comment by bepaald** [comment]
Excellent, thanks again for your detailed report.

**Comment by hugogithubs** [comment]
Hi again, 

sorry, but I think there is again an issue with read/sent status. 
(Should I have opend a new issue or is this ok for you this way?)

After merging some jan. / feb. files to my main backupfile I again have noticed, that something goes wrong with read / sent status. 
In the moment both files have database version 214.
It looks like only the newest merged messages have correct read/sent status set.

I don't know since when this issue came up because I don't always check the html export.

Do you need more information? 
In this context, is there perhaps a specific expression in the log file that I should pay attention to? 
There are no warnings or errors.

Best regards.

**Comment by bepaald** [comment]
>(Should I have opend a new issue or is this ok for you this way?)

No, this is absolutely fine.

>After merging some jan. / feb. files to my main backupfile I again have noticed, that something goes wrong with read / sent status.

That's curious, I don't know why that would happen now. Have you confirmed that the two databases, when exported as html individually have all correct read/sent statuses? I don't think there is anything in the logs (if there is no warnings/errors), except maybe if you see any messages saying _"Dropping column"_ or _"Translating column"_ (which I don't expect since both databases are 214).

Maybe you could find a message with an incorrect read/sent status in the merged backup, one with a somewhat unique message body, and run:

`./signalbackup-tools [input] [passphrase] --runsqlquery "SELECT has_read_receipt, has_delivery_receipt, viewed FROM message WHERE body LIKE '%MESSAGE_BODY_GOES_HERE%';`

And do that on both the original and the merged backup to see if information is indeed lost somehow between the two.

Thanks!

**Comment by hugogithubs** [comment]
Hi,
regarding this issue with wrong/not updated read/sent statuses in my merged file I think there is  a general problem:

I think it depends on the timing when the status changed: 

A merged backup file exist for the past period of time
1. Day :  
- During the day a message was sent to recipient but not read by recipient
2. Day:
- at 03:00 backup was created
- at  e.g. 10:00 statuss changed to read
3. Day;
- at 03:00 backup was created

After cropping and merging backup created on Day 2 the message is added as unread to the mergedfile.
If I crop and merge file of Day 3  the changed message is also cropped because it regards the message from day before and the new status is lost, because I think cropping deals with "createdate of message", and not "changed status of message".

Am I right with this  assessment?

**Comment by bepaald** [comment]
>Am I right with this assessment?

If I understand your theory completely, I don't think this is right. The cropping function does not revert the status of messages to the time of the crop. The day-1-message will be unread if imported from the day-2-backup and read if imported from the day-3-backup, regardless of any cropping.

Is it at all possible the unread messages happened because you accidentally kept the merged file from an old version of this tool (that contained the problem you opened this issue for)?

>P.S.: Since I wanted to eliminate this error in my longterm backup mergefile, I started from scratch and left out all the "historical" intermediate backups and was able to merge the oldest complete backup V201 into the newsest backup with version V214 without any error!!
After this I transfered it to "interim Version 215" with your custom_hugogithugs option and continued now up to V216 without any problems!! 👍

Sounds good! Does that now mean everything is back in working order? There are no status problems anymore?

Thanks!

**Comment by hugogithubs** [comment]
> > Am I right with this assessment?
> 
> If I understand your theory completely, I don't think this is right. The cropping function does not revert the status of messages to the time of the crop. The day-1-message will be unread if imported from the day-2-backup and read if imported from the day-3-backup, regardless of any cropping.

It is not a problem of cropping function,
What I meen is that:
The message will be merged/imported with status unread with first backup.

I always crop the next backup file to duration "last_backup_merged" to "now" . 

day 3 backup file:  the regarding message will then be **not** part of  this cropped part which will be merged, because this message was created days before.

Therefore the changed status of the message can not be updated anymore in the "target mergefile" because the crop date interval does not include the updated message anymore.

But sorry, I don't want to steal your precious time with all this. 

> 
> Is it at all possible the unread messages happened because you accidentally kept the merged file from an old version of this tool (that contained the problem you opened this issue for)?
> 
Yes this is possible, this is the reason I started again from scatch mentioned in my P.S.

> 
> Sounds good! Does that now mean everything is back in working order? There are no status problems anymore?

Yes! For now all fine!!
> 
> Thanks!

**Comment by bepaald** [comment]
Ah sorry, I get it now. Yes you are completely correct. Glad everything is working then. Thanks!
