### ISSUE TITLE
  You set the disappearing message timer to 2000 weeks

### ISSUE THREAD

**Issue by Outlet2048** [bepaald/signalbackup-tools#180]
I have changed my Signal Setting to delete messages for all parties after 2 weeks

The app shows this properly
the HTML export adds a few zeros
![grafik](https://github.com/bepaald/signalbackup-tools/assets/72819077/1a80686a-0771-41b8-b0f7-7f87019f2474)

**Comment by bepaald** [comment]
Haha, ok. Up until two weeks ago, these message types were not actually included in the backup, so while I wrote this code I did not actually know (or need to know) what the values looked like. Turns out they're in milliseconds, not seconds.

By the way, are you on the beta? I had seen expiring messages were being backed up now (if they expire in 1 day or more), but did not think the change was out in the wild yet.

Anyway, this should be fixed, please let me know if it looks better now. Thanks for reporting!

**Comment by bepaald** [comment]
Thanks!
