### ISSUE TITLE
Problem merging db Version 214 to 215

### ISSUE THREAD

**Issue by hugogithubs** [bepaald/signalbackup-tools#184]
Hi,

SW Version: 
signalbackup-tools (signalbackup-tools) source version 20240205.120839 (Win)

when merging file of db version 214 to newer Version 215 I get this error message:

```
[Error]: Source and target database at incompatible versions
[Error]: A fatal error occurred while trying to import thread 7. Aborting
```
There are no more info in logfile of merging task

**Comment by bepaald** [comment]
I'm sorry to have to report this is expected and intentional. Between some database versions, changes are made in such a way that they can't be merged. I happened to have linked you a bit of the code in a message in the other issue (https://github.com/bepaald/signalbackup-tools/issues/174#issuecomment-1875831329), but just shortly after I did that, this code was changed to also include dbv < 215 and =>215. This is due to a change in how attachments are stored and referenced in the database.

If this will be big problem, I could investigate a way to make this work (write a custom merge-function for these db versions). But it will certainly take a while before I could get around to it (if I can do it at all).

**Comment by bepaald** [comment]
I was thinking about this a little more during work, and I think it may not be too difficult to get the 214 database to a state where it can be used as a source for importing into a true 215 db. No promises, but I think it's doable in not too much time.

**Comment by hugogithubs** [comment]
Hi,
I'll test this soon and report here about result.
Many thanks for your effort!

**Comment by bepaald** [comment]
Excellent, thanks for the feedback. Happy it worked.

>It's hard to believe how much the developers at Signal constantly tinker with the database structure without noticing any changes in the frontend.

True. They definitely made a few design choices that enable them to do this a bit easier (certainly easier than in my tool). Though it's much easier if you don't actually try to do all these merging and importing operations _and_ don't support old version indefinitely. But, for this change from 214 to 215, even Signal had to add some custom extra code to the backup-restore function to keep working (that's rare!).

Thanks again!

**Comment by hugogithubs** [comment]
Hi,

regarding your new custom parameter function:
> `--custom_hugogithubs -o [output.backup]`
Perhaps this could be documented in help output so other people with same issue could have the chance to solve it by themself?

It's just a suggestion.

**Comment by bepaald** [comment]
I renamed the option `--migrate214to215` (old name also still works), and mentioned it in the `--help` output with a link to this issue. Thanks!
