### ISSUE TITLE
Reassociating attachement/media

### ISSUE THREAD

**Issue by lp35** [bepaald/signalbackup-tools#207]
Hi!

First I would like to warmly thank you for all the hard work you have done for this project.

As many Signal users, I have trouble to find a proper backup protocol. Signal backups embed all medias, and is not incremental, resulting of huge backup files that need to be synched over the air each time.

In order to solve this issue:

1.) Export all medias using the "Storage" section of Signal app
2.) Delete media from signal internal storage, resulting of making signal backup very small (only text in it)
3.) synch media through another way (e.g syncthing)

However, I would like to be able to reassociate conversation with media if needed. My question is:

Would it be possible, given a Signal backup where media have been removed through the signal app, to scan a folder of media and re-associate them in the conversation?

E.g: signalbackup-tool MYBACKUP --reassociate-images FOLDER_WHERE_MEDIA_ARE_STORED

Maybe there is a sort of "file-hash" definitely stored in signal backups, that would to reassociate with an existing media.

Thanks for your time!

**Comment by bepaald** [comment]
Hi!

Interesting problem.

>Would it be possible, given a Signal backup where media have been removed through the signal app, to scan a folder of media and re-associate them in the conversation? Maybe there is a sort of "file-hash" definitely stored in signal backups, that would to reassociate with an existing media.

I do not see a way to do this. As far as I know, after deleting an attachment, nothing in the database remains to indicate it was ever there.

Also please note:
> 2.) Delete media from signal internal storage, resulting of making signal backup very small (only text in it)

When deleting 'media' through signal, the _entire_ message the attachment belongs to is deleted, including any text component. If you're still able to create full backups (if you still have the free space for it), I'd sooner recommend exporting a backup and using this tools `--deleteattachments` option ([see here](https://github.com/bepaald/signalbackup-tools?tab=readme-ov-file#deleting-attachments)), or alternatively `--replaceattachments` ([here](https://github.com/bepaald/signalbackup-tools?tab=readme-ov-file#replacing-attachments)). Both of these options will keep the text-content of messages intact. Also, there is a handy script that uses this tool and `--replaceattachments` to replace attachments in a backup with shrunk versions: https://github.com/cycneuramus/signal-backup-shrink (I've never tested it, but last I heard it worked). Be sure to save an original backup when trying these functions, they seem to have worked fine so far, but I don't know how often they are used and with Signal's changing database scheme things could always be broken.

With these methods, especially `--replaceattachments`, things are less destructive, since the actual messages and the associated attachment entries in the database will all remain. This makes it at least theoretically possible to undo the replacement (at least for image-attachments). The hard part when undoing will be matching the replaced images with the correct originals (which again, I wouldn't know how to do, but it's at least _possible_ even if it has to be done manually).

Thanks!

**Comment by lp35** [comment]
Thanks for your very complete answer.
I guess it is not possible to store extra metadata/entries in the signal database without breaking it? For example, adding a DB entry called "signalbackup-imagehash"?

Otherwise I thought about a (nasty) hack: 
1. Extract image
2. reshrinking to a very, very small image
3. add a metadata to the jpeg with 2 custom exifs: name of the exported file + md5 hash of the image.
4. Reinsert image in the backup

What do you think about that?

Cheer!

**Comment by bepaald** [comment]
> I guess it is not possible to store extra metadata/entries in the signal database without breaking it? For example, adding a DB entry called "signalbackup-imagehash"?

I think this is probably possible, if added in a separate table (on updates, tables are occasionally rebuilt, which would cause any added columns to be dropped again). Also, while right now during backup creation Signal will just export all database tables, excluding a specific list (blacklisted), any future update might change this behavior to only export a specific list (whitelisted) in which case all your extra data is lost again.

All in all this sounds like a bad idea to me, certainly a much nastier hack than your second option.

> Otherwise I thought about a (nasty) hack:
> 
> 1. Extract image
> 2. reshrinking to a very, very small image
> 3. add a metadata to the jpeg with 2 custom exifs: name of the exported file + md5 hash of the image.
> 4. Reinsert image in the backup
> 
> What do you think about that?

That is much cleaner I think, it produces a completely valid, normal backup with modifications that should last forever. (though Signal itself normally strips exif data when attaching an image, I don't think it touches the files after they are in the database). Also, this should be easily scriptable, pretty much like the script I linked to in my previous message but with the extra step of adding the exif data to the new small files. I must admit I know next to nothing about exif data, I assume it allows for custom tags with custom values?

**Comment by bepaald** [comment]
I think we're done here? Let me know if you need any more help from me. Thanks!

**Comment by bepaald** [comment]
Honestly not sure what to do with this comment, I'm not sure I fully understand it, it's very abstract.

A few points that popped in my head while reading, not sure if they're helpful:
- It is true the encrypted data can not be delta-compressed (due to the encryption). But this tool can easily decrypt a backup to a directory. Delta-compression should work on that (at least somewhat, for the sqlite database, there may be better ways, like sqldiff). Doing this will also show you a fairly raw format of the 'Signal backup once encryption is removed'.
- There is talk of a 'manifest'. Indeed no stable message _id is available. Currently messages in the database have a unique constraint on `date_sent, from_recipient_id, thread_id` (in one thread, one contact can send one single message at any time). This _would_ identify a message, _BUT_: database columns get renamed occasionally (`date_sent` used to be `date`, `from_recipient_id` used to be `recipient_id`, though it's not even really equivalent). More importantly, in the past database migrations have altered not only the `_id` of messages but also their `date_sent`. So even this is not reliable way to reference a message. The only working 'manifest' would be to just use the actual sqlite database (which this tool will save to the directory when decrypting), though it will only be reliable for _that specific backup_, and not necessarily for the next one.
- There is mention of re-attaching media to the messages (using the manifest). As mentioned before, messages with no body-text (very common for media messages I think), are deleted when the media is deleted. So a new problem shows up: you need to first re-insert the (deleted) message, before you can re-attach the media.

I still think what **lp35** suggested [earlier](https://github.com/bepaald/signalbackup-tools/issues/207#issuecomment-2067723858) is the best solution. It does not require any manifest, no messages get deleted and shouldn't be too hard to implement.

Otherwise, you could write scripts to deal with the decrypted data this tool provides in any way you like, so I'd say study the data and go for it. And let me know if you have any specific questions about the database.

---

Lastly I feel I should note the current backup format as a whole will be retired at some point. Whether it's in a month or in a few years, I don't know, but Signal has been working on a backupV2 for a long time and it's getting closer and closer. I don't yet know the specifics of that new format too well, but without a doubt any incremental backup, or delta-compression between the old and new formats is doomed to fail. (and this tool will likely need to be re-written). That's something to be aware of when deciding how much time and effort you put into it at this point.

Thanks!
