### ISSUE TITLE
Database merge success

### ISSUE THREAD

**Issue by nkm8** [bepaald/signalbackup-tools#21]
Per the documentation, I just wanted to drop a note of thanks - I was successfully able to merge 2 signal databases - both database versions were 87. 

I had to drop to an old version of Signal to import my SMS messages. I updated Signal before merging the databases, so I didn't rely on the tool for that. 

The merged database successfully restored on the latest version of Signal 👍

**Comment by breversa** [comment]
Thanks for you report ! Could you add which Signal version(s) were used ?

**Comment by bepaald** [comment]
@nkm8 Thanks so much for your report. I'm happy the merger worked for you. I have been having quite a few success reports, both here and via email lately, so I'd almost say it's time to remove that disclaimer from the readme. Then again, I only just had an email from someone where it did not work (completely) which led my to find (and fix) a bug: 2b3eb88. So, I'll give it just a little more time. Thanks again!

@breversa I assume you'er asking for the Signal versions because the sms-import seems to have been removed in the latest version? In that case, I've had an email from someone just last week who did the exact same procedure as nkm8 mentions above: he said he downgraded to 5.0.8 in order to import the sms messages, then upgraded and exported a backup.

Closing this, just as clean-up, but feel free to follow up or open a new issue.
