### ISSUE TITLE
Does this work with desktop storage file from Session Messenger?

### ISSUE THREAD

**Issue by bram-pkg** [bepaald/signalbackup-tools#214]
Do you happen to know if this tool works with the state file that Session Messenger has on your PC?

**Comment by bepaald** [comment]
Good question, I don't know.

I'm not sure what this 'state file' is (not familiar with Session at all really, I'll answer as best I can, but it may be lacking).

On the Android side, this tool only works with Signal Android backup files. While Session is a fork of Signal, it does not seem to support backups, so that will not work.

For some features, a Signal Desktop database is also read (in order to import its contents into an Android backup, for instance). And I see Session Desktop is again a fork of the Signal software. So, depending on how much they've changed it may or may not be possible to read. Signal Desktop keeps its data in a directory containing two (important) files:  `config.json` and `sql/db.sqlite`. If Session has these same files available somewhere you can simply try and see if they work. Use `--desktopdirs` to pass the right location (assuming it is not the standard Signal location), or copy and rename files as necessary.

Let me know if I can be of any more help. Thanks!

**Comment by bram-pkg** [comment]
Thanks for the quick response! I will check it.
