### ISSUE TITLE
add readme infor about difference --limittothreadsbyname and --croptothreadsbyname

### ISSUE THREAD

**Issue by Meteor0id** [bepaald/signalbackup-tools#221]
I just realized there are two variants and had not seen any info on the difference. Maybe add something about that in the readme?

**Comment by bepaald** [comment]
These are not two variants of the same thing.

`--limittothreads(byname)` is a modifier for various export function (like html or txt). This does not alter the actual backup file, it just modifies the behavior of the export. That is `./signalbackup-tools [input] [passhrase] --exporthtml [HTMLDIR] --limittothreads 1,2,3 --output [OUTPUTFILE]` will produce an `OUTPUTFILE` identical to the `input`.

`--croptothreads(byname)` is a top level function (not a modifier of another) and alters the input backup file: `signalbackup-tools [input] [passphrase] --croptothreads 1,2,3 -o [OUTPUTFILE]` will generate a new, modified backup file that only contains threads 1, 2 & 3 that can be restored in Signal Android.

Each of these options is mentioned in the README, the former as a modifier to all the options it works with ([html](https://github.com/bepaald/signalbackup-tools?tab=readme-ov-file#export-to-html), [txt](https://github.com/bepaald/signalbackup-tools?tab=readme-ov-file#export-to-txt), [dumpmedia](https://github.com/bepaald/signalbackup-tools?tab=readme-ov-file#dumpmedia)), the latter as one of the two [cropping](https://github.com/bepaald/signalbackup-tools?tab=readme-ov-file#crop-to-threads) options (the other being `--croptodates`, which has its own modifier-counterpart for the export functions named `--limittodates`).

**Comment by bepaald** [comment]
I believe this issue can be closed without further action, but let me know if you disagree.

**Comment by Meteor0id** [comment]
> Each of these options is mentioned in the README, (...) the latter as one of the two [cropping](https://github.com/bepaald/signalbackup-tools?tab=readme-ov-file#crop-to-threads) options

thanks for the explanation, but maybe some mention of this difference could be in the readme, since in some cases both options could be used which confused me (but that might just be me)

**Comment by bepaald** [comment]
I've looked at this some more, but I really don't see how I could easily make it more clear than how it's written. The only way to really confuse the two is if one simply guesses their existence or by reading the source code without looking at what they do.

If anyone simply reads the README or the output of `-h/--help` (which should be the only way one even learns these options exist), I don't think there should be any confusion.

Thanks!

**Comment by Meteor0id** [comment]
@bepaald maybe the story privacy (list of excluded contacts) is not affected by cropping, I could test that later. I guess it isn't meant to be affected but in that case there is no way to use the tool to affect listed contacts there.

**Comment by bepaald** [comment]
>@bepaald maybe the story privacy (list of excluded contacts) is not affected by cropping, I could test that later. I guess it isn't meant to be affected but in case there is no way to use the tool to affect listed contacts there.

I've read this a dozen times now, but I'm afraid I don't really understand what you are saying here. I'm probably just dense, but maybe you could clarify?

Just a few remarks that may or may not be relevant:
- The removal of contacts when cropping is purely a side effect of the (way I implemented the) procedure. It drops all contacts that are not referenced by anything remaining in the database.
- Since Signal requires the _"my story"_ recipient to be present (ref: [#223](https://github.com/bepaald/signalbackup-tools/issues/223)), this one is always kept. (This is the recipient that `--listrecipients` will show as `display_name = 00000000-0000-0000-0000-000000000000`)
- A side effect of the above two points is that all the contacts that receive _"my story"_ posts are also kept since they are referenced by this story through the `distribution_list` and `distribution_list_member` tables. The work-around for this, as far as one is needed, is to make sure to remove all recipients of the _"my story"_ posts before cropping.

Not sure that has anything to do with what you were saying, but there you go :-)
