### ISSUE TITLE
Windows .exe is able to read backup, but errors when exporting to xml.

### ISSUE THREAD

**Issue by twhoeksema** [bepaald/signalbackup-tools#23]
I ran this today on my laptop running Windows 10 x64 version 2004 and it does read the entire backup. But when it says its exporting to the specified file it throws 4 identical errors (in my case anyway).  This is what I get at the end:

Reading backup file...
FRAME 84066 (100.0%)... Read entire backup file...

done!

Exporting backup to '.\Signal-decrypt-sms.xml'
ERROR Failed to retrieve required field 'address'
ERROR Failed to retrieve required field 'address'
ERROR Failed to retrieve required field 'address'
ERROR Failed to retrieve required field 'address'

Any idea what this could be? It has me scratching my head as to what could cause it.

Upon inspection of the file properties, I see that theres something in the .xml however idk if there is anything missing.

Have a good night,
T. H.

**Comment by bepaald** [comment]
Thanks for you report. Since the groups in Signal have updated to GroupV2, some messages without a sender can appear in chats (system messages, like 'This group was updated to a New Group'). Since these messages have no sender, but the xml specification requires a sender (in the 'address' attribute), this is an error.

I thought I had worked around this in the code (it works for me), but apparently there are more message types (probably group updates) that fail. I will investigate and hopefully have a fix later today.

**Comment by bepaald** [comment]
Upon reading back the source code, I think it is quite likely that some messages were missing from the XML, but the fix I sent earlier should have fixed that.

I would be very interested if you still have the same error when using the current version (https://github.com/bepaald/signalbackup-tools/releases). The error indicates that a message was sent by/to a recipient without a phone number. Up until recently this wasn't possible in Signal, but it is planned for a long time, and I have had some indication that maybe this is now happening. Note, that contacts without phone numbers cannot comply with the xml spec (https://synctech.com.au/sms-backup-restore/fields-in-xml-backup-files/ and https://synctech.com.au/wp-content/uploads/2018/01/sms.xsd_.txt), so I wouldn't really know what to do with them yet.

If you want to be sure all message are there (excluding what is noted in the readme), you could run:
`./signalbackup-tools  --runprettysqlquery "SELECT COUNT(*) FROM sms WHERE type != 9" [INPUTFILE] [PASSWORD]`
This should show the number of messages in the sms table of your database, and should match the number of lines in the output minus 4. Note, type  9 messages are excluded, since they are special (system generated) messages about a old group being updated to groupV2.

**Comment by twhoeksema** [comment]
Okay I will look into it over the weekend and get back to you. 👍

**Comment by twhoeksema** [comment]
I suppose if I knew which message went where, I could add the address in
manually

**Comment by bepaald** [comment]
Is this still an issue? Did you try the current version? And checked the number of messages as described in my last comment? Can this be closed?

**Comment by twhoeksema** [comment]
I will need to take a second look at it once I'm back home from vacation
later today, but I think it still is. If not the exact same error, then
something similar.

**Comment by bepaald** [comment]
Just closing for lack of response. Please feel free to open a new issue of there is a problem still (though with the upcoming database changes XML export will probably break in other ways). Thanks!
