### ISSUE TITLE
Memory usage with merging

### ISSUE THREAD

**Issue by junoslukan** [bepaald/signalbackup-tools#24]
When merging an existing database (6 MB) with a large source database (380 MB) I quickly ran out of memory. RAM usage steadily increased with each thread processed, until I ran out both of RAM (4 GB) and cache (4 GB).

Would it be possible to free up memory after processing each thread?

I bypassed the issue by selecting only a small number of threads (by using `--importthreads`), but ideally I would like to import all of the threads from the source database.

Other than that, I didn't run into any other problems, so it seems that merging works fine. Good job! 

I did get a lot of 

> Column not present in target database

and a

> NOTE: Skipping table 'megaphone', as it is not present in target database. Data may be missing.

at each thread, but that's probably just database incompatibility (versions 80 and 89) as you have already mentioned they change rather frequently.

**Comment by bepaald** [comment]
Thanks for your report. A similar case was reported to me via email a week or two ago. Trying to reproduce (and fix) it is on my to-do list. The other case was using Windows, are you using Windows as well?

Please note, that memory is (or should be) cleaned up after processing each thread. I regularly test merging my own databases (which are around 4GB) and memory usage during the whole process is completely as expected (which is basically minimal considering the sizes of the backup files).

If you are using Windows, it would be very helpful if you could test the same process, with the same databases, on a Linux machine, that way I can know if it is a Windows specific problem, or something else. Could you also tell me something about the source database? In the other reported case, the source db had an unusually large number of threads, does yours have that as well? Some info about the databases, with thread- and message-counts should have been printed when started the merge.

Thanks!

**Comment by cowlicks** [comment]
I'm currently try to merge two backups, one 9.3G and the other 8.4G on a system with 16 GB of ram. The process is eventually killed because I run out of memory and eventually run out of 8GB of swap

**Comment by cowlicks** [comment]
@bepaald Any estimate on how big a system I'd need? The backups overlap **a lot**. I'm on arch linux.

**Comment by junoslukan** [comment]
Hi @bepaald , I was using Ubuntu 20.04 for this process.

The source database included 250 threads. Some of these were very large and old (the oldest from around 2013). 

I am not sure how to get the message count per thread, but it says 
```
Reading backup file...
FRAME 25523 (100.0%)...
```
if that's actually message count.

Let me know if you need any more info.

**Comment by bepaald** [comment]
Ok, so I finally had some time to check memory usage and the program was indeed not behaving as designed, I just never noticed because of an abundance of RAM I guess. And I haven't been running the program through valgrind since I rarely touch the core functions and my smallest test-script takes over 15 hours when running through valgrind.

Anyway. I stupidly introduced a nasty memory leak in https://github.com/bepaald/signalbackup-tools/commit/6ee78632252bcc545f191c2667606a8026f754e7#diff-92f38acb19acd37957e66ec368cf2537c9cc120fa210ca8bbdcbad0a9c667499 back in November.

It should now be fixed. Memory usage during a merge, in practice, is mostly determined by the largest attachment. Probably about twice the largest attachment + a couple MB for the database and some overhead. When merging two 4,5GB backups, memory usage peaks when writing the output at about 250MB. Largest attachment in those files is 100MB (I think that's actually an app limit). Please, if possible, both of you try again and report back.

@cowlicks Memory should no longer be an issue. What do you mean about the overlap though? Is that just in timeframe, or are there actually duplicate messages in the two files? Note that in the latter case, it would be wise to `--croptodates` before merging (though a `--removedoubles` option also exists for use after merging, but it is less well tested).

@junoslukan Thanks for the info. As said, I think the problem is solved, but just in case: when merging, after each database is read for the first time, a summary of it is printed that looks something like this:
```
Target database info:
Database version: 85
Filesize: 4622385502 bytes
Period: 2016-09-03 16:44:03 - 2021-01-01 00:00:25
Tables:
sms : 50808 (per thread: 5700,24,153,209,101,114,50,14125,5,1136,755,3781,1003,380,595,346,16936,17,1032,36,15,54,185,2524,843,132,60,7,281,2,2,39,63,93,1,9)
mms : 4394 (per thread: 256,95,13,2,6,51,582,1,132,57,367,549,32,43,9,805,2,323,40,1,2,240,221,266,31,33,1,80,2,12,78,59,3)
part : 3321
thread : 36
identities : 23
drafts : 0
push : 0
groups : 21
group_receipts : 3016
signed_prekeys : 0
one_time_prekeys : 0
sessions : 0
sms_fts : 50808
sms_fts_data : 363
sms_fts_idx : 340
sms_fts_docsize : 50808
sms_fts_config : 1
mms_fts : 4394
mms_fts_data : 38
mms_fts_idx : 36
mms_fts_docsize : 4394
mms_fts_config : 1
job_spec : 0
sqlite_sequence : 3
constraint_spec : 0
dependency_spec : 0
sticker : 31
recipient : 88
storage_key : 0
key_value : 0
megaphone : 9
remapped_recipients : 0
remapped_threads : 0
mention : 0
```

That would be the info I need.

**Comment by bepaald** [comment]
Well, I assume I got the bug and the issue is resolved. Feel free to open a new one if this is still a  thing. Thanks!
