### ISSUE TITLE
[Enhancement] split html backup by date

### ISSUE THREAD

**Issue by aboulan** [bepaald/signalbackup-tools#245]
Hello,
It would be really nice if the html export ( --exporthtml --split ) could be split by date instead of a fixed number of messages.
For example, one page per month (or year, for less active threads)
Thanks for this great tool !

**Comment by bepaald** [comment]
Yes, I'm ok with this. I gave it some thought and it should be doable, I'll work on this when I find some time. Hopefully the next few days.

Thanks!

**Comment by bepaald** [comment]
I had a go at this, it was less difficult than I feared (suspiciously so even). I gave it a quick test but it's possible I'm not considering all corner cases.

Try it out, see if it behaves as you'd expect. Use `--split-by [period]`, where supported period-values are 'year', 'month', 'week', and 'day'. Let me know.

Thanks!

**Comment by bepaald** [comment]
I believe this option is implemented and working. If not, let me know, this can always be re-opened.

Thanks!

**Comment by aboulan** [comment]
Hello,
Thank you for having implemented this option so fast!
I have just tested it and it seems to work well on my database (which is pretty big, almost 20GB over 6 years)
However, I have found a small issue where sometimes some messages of late Dec. 31th  appear incorrectly at the beginning of the next page for Jan. 1st. There does not seem to be an issue for other months in the year (but I haven't checked all the pages)
I will try to have a look into the issue.
Regards,

**Comment by bepaald** [comment]
Thanks for the feedback. I will look into it.

First thing I can think of: messages have a `date_sent` and a `date_received` property. While the time shown on the message bubble in the application (and in the HTML export) is the `date_sent`, the actual order of the messages is the `date_received` (which makes sense, it can't place a message until it has been received).

For the split I am also using the `date_received`, but maybe in the case you describe such a message was sent on Dec 31, but only received on Jan 1. This would cause the message to move to the next page (`date_received` = next month), while its bubble would say Dec 31 (`date_sent` = previous month).

You could check this theory by running:
```
signalbackup-tools [input] [passphrase] --runprettysqlquery "SELECT DATETIME(ROUND(date_sent / 1000), 'unixepoch', 'localtime') AS date_sent, DATETIME(ROUND(date_received / 1000), 'unixepoch', 'localtime') AS date_received FROM message WHERE body LIKE '%some_unique_string_from_the_message%'"
```
(obviously replace `some_unique_string_from_the_message` with some of the message body to select that specific message)

I could possibly simply split the pages by `date_sent` instead but I need to think about the implications of that, maybe it can cause a similar problem reversed. I feel this would be correct, but I'm late for something right now, so I'll think about it when I have some time.

Thanks!

**Comment by aboulan** [comment]
Seems you guessed right. Here is the result for the first of these messages:

---------------------------------------------
| date_sent           | date_received       |
---------------------------------------------
| 2021-12-31 21:23:59 | 2022-01-01 02:00:38 |
---------------------------------------------

So, as you said, maybe you can split by date_sent. If signal cannot receive messages out of order (?), I don't think there can be any issue with that.
But on the other hand, I don't mind the current behavior, as long as it is now understood that it is not a bug (and it reminds me that new year messages take some time to be received :)

Thanks!

**Comment by bepaald** [comment]
Thanks for the quick reply.

> If signal cannot receive messages out of order (?),

Unfortunately, Signal can (and does) receive messages out of order. While I assume the messages arrive in order from the message queue on Signal's server, the delayed message, sent at 21:23:59 may not have _arrived_ at the server until 02:00:37 on Jan 1, and any number of other messages could have arrived and been delivered in those 3.5 hours.

Furthermore it should be noted that the `date_sent` is simply the time on the senders phone at the time of pressing the send button. If the contact has the date settings on their phone set manually (and incorrectly), or they are traveling through different timezones, the `date_sent` could really have any random value. I have many messages in my backup (from people in planes, and from people with manually set times) that have a `date_sent` that appears in the future compared to the `date_received`.*

So, imagine a case like yours, where the delayed message is sent in a group chat. And right after midnight, people start wishing each other happy new year (not too far fetched I think):
```
(dec 31, 23:59) -> happy new year! (1)
(jan 01, 00:01) -> happy new year! (2)
(jan 01, 02:00) -> happy new year! (3)    <- this is the delayed message with a sent_date on Dec 31, 21:23.
```
How would I split? 
- If by `date_received`, we get the situation you have now: one message with a message-bubble saying December is put in the January HTML.
- If by `date_sent` things get tricky. Since messages are processed in order (and the order is `date_received`), a split would be made between (1) and (2), and then another split between (2) and (3). Currently this would cause two HTML files for December to be created, the second one containing only the delayed message. I could of course attempt to append message (3) to the existing December HTML, but this would effectively be the same as:
- Actually order the messages by `sent_date`, and then split by `sent_date`. This would cause (3) and (1) to appear in December (in that order), and (2) in January. But ordering by `sent_date` would cause the HTML to no longer be a true representation of events. In Signal, the above case would appear exactly as written above (1), then (2), then (3). Ordering by `sent_date` would be a huge problem, where conversations could appear completely out of sync, messages appearing to respond to a different message than they actually responded to, answers appearing before questions etc.

>But on the other hand, I don't mind the current behavior, as long as it is now understood that it is not a bug (and it reminds me that new year messages take some time to be received :)

As far as I can tell, there is no error-free solution to this, and I am inclined to leave it as it is. But I'm very open to suggestions, maybe I'm not thinking clearly. Let me know if you have any ideas! If not, I think this issue can be closed again, unless you find any other odd behavior.

Thanks again!


\* Note, this has actually led to some code changes. While until now I had the message bubble always display the `date_sent`, the correct way is to actually take the earliest timestamp of `date_sent` and `date_received`. You can expect this change when I next push an update.

**Comment by bepaald** [comment]
Ok, I agree. Thanks again, let me know if there's ever anything else.
