### ISSUE TITLE
This app is not compatible with your computer

### ISSUE THREAD

**Issue by viiktr** [bepaald/signalbackup-tools#247]
When I try to follow the tutorial [here](https://transistor-man.com/restoring_android_signal_from_desktop.html) everything goes well until Windows 11 throwing "This app is not compatible with you computer". I use Windows 11 with the most recent version of the tool 
Removed the image because my code was showing.

**Comment by bepaald** [comment]
Hi!

I've never seen this before, I'm not sure what's going on. I'm not a Windows user myself, so my knowledge is somewhat limited, but from what I know, this error might show up if your system architecture is different from the app (x86_64). However, after a short search it seems that Windows 11 does not support 32 bit systems anymore, and Windows on ARM reportedly runs x86_64 programs without problems. I will need to investigate this a little more.

- Could you tell me what processor is in that computer?
- Could you also try to give a full translation of that error message? I tried Google translate but I don't think it's very accurate.

Thanks!

**Comment by viiktr** [comment]
Hi @bepaald 👋🏻
Here is the data about my computer:
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
System type	64-bit operating system, x64-based processor

Here is the exact error in EN:
![image](https://github.com/user-attachments/assets/d833c6d0-5480-4dd2-8973-d2b0b11d3163)

The release of the tools is the one from 12 hours ago
Thank you!

**Comment by bepaald** [comment]
Thanks for the quick response. Unfortunately, that still doesn't give me any ideas.

I did just download a Win11 virtual machine from microsoft for testing. For me, the program runs perfectly fine. One thing I did notice, is I had to write `.\signalbackup-tools_win.exe`, including the `.\` or else it didn't work. I notice in your first screenshot you do no have the `.\` in there, so maybe that has something to do with it. Although I did get a different error (command not found), and it may just be because I used a different terminal (PowerShell). But I just wanted to mention it quickly before I left for work.

I'll think about this some more later today, I hope I can think of something. Thanks!

**Comment by viiktr** [comment]
A short update, it worked. If somebody in the future stumbles upon this just use PowerShell. Cmd will return the this app can;t run on your PC, no matter how you wrote it. 

The line I used in PowerShell was **.\signalbackup-tools_win.exe** [backup file name] [your code] --importfromdesktop --output [new_database_output] . The .\ and switch to PowerShell made the change. The chats have been restored successfully

**Comment by bepaald** [comment]
Great to hear! I'm glad you managed to solve it, since I still really had no clue why this was happening.

Just for the record: I have by now tested the program on Windows 11, both in a virtual machine and on bare metal, and in both cases it works fine with PowerShell _and_ Cmd. I think there is no bug in this program in that causes this and there is probably some setting or issue with your PC (or cmd version, or whatever).

Either way, using PowerShell in place of Cmd is good advice regardless, and users facing this same issue should definitely switch.

Thanks for the feedback! I'm happy your chats are restored. Cheers!

**Comment by bjjnpy** [comment]
Hello,
I've also tried to restore chats according to the manual linked above. I've got the same error message as @viiktr ("This app is not compatible with your computer").
Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz
System type: 64-bit operating system, x64-based processor.
Tried to use 

> .\signalbackup-tools_win.exe [backup file name] [your code] --importfromdesktop --output [new_database_output]

 command in PowerShell but not worked.

![signal](https://github.com/user-attachments/assets/85130d33-781e-4c57-ab76-02455608aea6)
