### ISSUE TITLE
Merging Backups worked like a charm

### ISSUE THREAD

**Issue by guwidoe** [bepaald/signalbackup-tools#25]
I used the --importthreads ALL option to merge two backups, more specifically I imported a 500MB Backup into a 35MB Backup and everything pretty much worked like a charm. 
The only error messages I saw were some 
```
SQL error after sqlite3_step(): UNIQUE constraint failed: remapped_recipients._id
SQL error after sqlite3_step(): UNIQUE constraint failed: remapped_recipients._id
SQL error after sqlite3_step(): UNIQUE constraint failed: remapped_recipients._id
```

for every thread that was imported. 
This didn't seem to harm the output though, as the newly created database worked perfectly when restoring it on a new phone.

Thanks a lot for this useful utility!

**Comment by bepaald** [comment]
Thanks!

But... bad news, I think those `SQL error after sqlite3_step(): UNIQUE constraint failed: remapped_recipients._id` messages are actually bugs. It is possible that everything has worked fine, but the merged database _may_ have become corrupted. I _think_ any errors should be limited to emoji-reactions, where if you have a message with a reaction, the author of the reaction may be incorrect (or actually point to a non existing author, leading to a crash).

The 'remapped_recipients'-table is very new, it appeared in the database a couple of updates ago, but in all databases I have seen or heard of, this table is empty. As a result, I only know of it's purpose and functioning by reading the java source code. If you have any specific knowledge of how you got an entry in this table, I would love to know so I can create a database for testing.

I have just pushed an update to hopefully deal with this table correctly (though I can't be sure, because I can't test). If you can, you might want to redo the merge and (thoroughly) check the resulting database, especially any reactions. Also, the merging will produce a lot more output which I would love to see. There may be some personal information in there though (names and phone numbers), so either delete those lines, or email them instead of posting here (or both). I might also be able to tell from the output whether your first merge was good or not.

I have only updated the source code right now, if you are using Windows  and want to redo the merge, please let me know and I'll update the executable.

Sorry for the trouble, it's really hard to keep up with the changes in Signal's database format sometimes.

**Comment by guwidoe** [comment]
Hi,

Interesting. I think any possible corruption caused by this shouldn't really be of any concern since importing the new backup worked fine and when creating a new one, potential corruption should be ironed out..., some possibly wrong emoji reactions are of limited concern to me. Unfortunately, I don't know how I got an entry in this table...

I can provide you with the log, I removed all 5+ digit numbers in it though because the phone numbers of my contacts appeared in it.
[log_old_numbers_removed.txt](https://github.com/bepaald/signalbackup-tools/files/5976346/log_old_numbers_removed.txt)

I tried merging the exact same files again with the updated binary and the original error messages indeed seem to be gone, however, a new error message emerged for every thread:
``` 
SQL error during sqlite3_prepare_v2(): no such table: recipient_preferences
```
I can't share this log though because more information regarding my contacts appears now and I can't immediately write a regex to get rid of them...

**Comment by bepaald** [comment]
>when creating a new one, potential corruption should be ironed out

Well I may be mistaken, but I do not believe this is the case. Also, there is the potential, not for a wrong emoji reaction, but one that will crash the app when it tries to render it. But also possibly not. Or maybe only when tapping the reaction to see its details (ie the sender).

I could, if you wanted, also maybe just write a bit of code to check if your database is in a proper state.

> I tried merging the exact same files again with the updated binary and the original error messages indeed seem to be gone, however, a new error message emerged for every thread:

Thanks! That was a stupid mistake in my code, it should be fixed now.

I have come up with some theories about how I could end up with remapped_recipients in my own database, I'll be trying that when I have time (hopefully tomorrow), so I can start testing and fixing myself.

**Comment by guwidoe** [comment]
Thanks for the info!
I am not too worried about it tbh, if you really want to write the DatabaseChecker I'd try it, but it doesn't really contain any critical data so don't worry... If one day, I end up having problems with my Signal app, it's good to know a potential source.
Thanks again for the tool!

**Comment by bepaald** [comment]
If I ever manage to get some remapped_recipients I'll probably end up writing a check anyway, but it's good to know I'm in no hurry :). Thanks!
