### ISSUE TITLE
Cannot get desktop key on Linux Mint xfce

### ISSUE THREAD

**Issue by ernstblaauw** [bepaald/signalbackup-tools#252]
As I am moving from Linux Mint xfce to KDE Plasma, I need to move the Signal key. As described [on Reddit](https://www.reddit.com/r/signal/comments/1fb79vp/comment/lqrvmre/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), I tried to use your tool to extract the Signal key from my Signal install. Signal works fine, and I am on version 7.28.
I installed signalbackup-tools using nix
I ran signalbackup-tools via `sudo nix-shell --packages signalbackup-tools -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz`
I tried running 
```
$ signalbackup-tools --showdesktopkey
signalbackup-tools (signalbackup-tools) source version 20240929.123459 (SQlite: 3.46.0, OpenSSL: OpenSSL 3.0.14 4 Jun 2024)
[Error]: Failed to open input: /config.json
[Error]: Failed to open input: /config.json
[Error]: Failed to get sqlcipher key to decrypt Signal Desktop database
```
and

```
$ signalbackuptools /home/<user>/.config/Signal --showdesktopkey
signalbackup-tools (signalbackup-tools) source version 20240929.123459 (SQlite: 3.46.0, OpenSSL: OpenSSL 3.0.14 4 Jun 2024)
[Error]: Failed to open input: /config.json
[Error]: Failed to open input: /config.json
[Error]: Failed to get sqlcipher key to decrypt Signal Desktop database
```
What should I do to get the key?

**Comment by bepaald** [comment]
Hi! My guess is, that running inside nix-shell prevents the tool from accessing your environment variables, so it can not find $HOME (and subsequently can not find you signal data directory).

You seem to have attempted to mitigate that with your second command, but unfortunately it's not fully correct. To specify the location of the Signal Desktop data folder, use `--desktopdirs` followed by the data folder (`/home/<user>/.config/Signal`) _twice_:
```
signalbackup-tools --desktopdirs /home/<user>/.config/Signal /home/<user>/.config/Signal --showdesktopkey
```
The doubling of the folder is for historical reasons, and has already been changed, but I see the nix package is (slightly) out of date so you need to pass it like that.

If the problem is not that the nix shell can't find you home directory, buy that it doesn't have access to it, then I don't know, there is probably some config option for that or you need to run the tool outside nix-shell.

Let me know if this helps!

**Comment by bepaald** [comment]
I have quickly run Linux Mint XFCE in a virtual machine to test. When running the program in a nix-shell, it indeed can not find home directory automatically. Manually specifying it as I described above helps with this. I have (locally) added a warning when the tool fails to determine Signal Desktop's data directory, which also advises the user to add `--desktopdirs`.

However, after that, the tool needs to access the `dbus` system to query the keys, which will also fail. I do not know enough about nix to solve this, there may be a way but I wouldn't know how. I can tell you that the tool worked fine on Mint XFCE when running in a normal shell.

**Comment by ernstblaauw** [comment]
Thanks, I will try to compile it myself and then run it. Your help is much appreciated!

**Comment by bepaald** [comment]
Since I still had my virtual machine going, just thought I'd show what I did to compile on Mint. There are of course other options, not using `cmake` or `git`, but I think this is easiest:
```shell
$ apt install g++ git cmake libssl-dev libsqlite3-dev libdbus-1-dev #installing deps, you may have them already
#[...]
$ git clone https://github.com/bepaald/signalbackup-tools #download the latest version of the tool
#[...]
$ cd signalbackup-tools
$ cmake -B build
#[...]
$ cmake --build build -j$(nproc) # build!
```

That was it, the executable can then be found in the `build` directory, and just running `./build/signalbackup-tools --showdesktopkey` should hopefully be it. Let me know how you get on.

**Comment by ernstblaauw** [comment]
Yes, it works!! Thanks a lot!! After obtaining they key, I copied my database to my new installation and used the ‘key’ var in config.json. Next to that, I had to change the password store from ‘libgnome…’ to ‘kwallet6’ in config.json (not sure what the old value was)

**Comment by bepaald** [comment]
That good to hear. I forgot about the `safeStorageBackend` in the config (it wasn't there when key encryption was first introduced), but you solved that. I think you probably could have gotten it working by removing that line completely. I should probably edit my reddit post to mention this.

Anyway, happy it worked in the end, and thanks for the feedback!
