### ISSUE TITLE
HTML export with clickable urls

### ISSUE THREAD

**Issue by jathri** [bepaald/signalbackup-tools#253]
Thank you for https://github.com/bepaald/signalbackup-tools/issues/251 again! Have another feature proposal. Another part of "convenience package" ;) Can it be implemented sometime? Since Signal desktop app contains clickable links as well. Perhaps it can be yet another switch.

**Comment by bepaald** [comment]
Yeah sure. This was always planned, but it quickly dropped in priority on the (back then) long to-do list when I discovered how difficult it was :-). Things have slowed down enough to tak e another crack at it though.

I actually believe I have something working now (locally), it's not perfect, but I think it works the same as Signal's linkify function (it's more or less copied from Android Open Source Project).

When I find some time (I'll be busy for the next few days), I will clean my code up and then find some way to integrate it with the project. I'll get back to you when it's done. 

Thanks!

**Comment by bepaald** [comment]
There is now initial support for this. This one was quite difficult, it could do with a lot of thorough testing.

Notes:
- There are known valid URL that aren't detected. I think (hope?) they are rare, and Signal does not detect them either, but still. (For example, none of the URLs mentioned [here](https://stackoverflow.com/questions/827557/how-do-you-validate-a-url-with-a-regular-expression-in-python/827621#827621) are linkified).
- There are some false hits, at least in my backup, around typos where erroneous `.`'s are present. Again, Signal does this too, and there is not really an issue (the tool simply can't know the intention of the user).
- When links without a protocol are present (`www.example.com`), these would normally be interpreted as relative paths to the current location. Normally, this can be worked around by prepending `//`, but that would default to the current protocol, which in this case would be `file://`, which would not be correct. I'm therefor always prepending protocol-less URLs with `https://`. This could produce dead links if the target does not support `https`. Again, I see no way around this.

For testing, please try to just look at as many URLs as you can (I realize manually checking each individual one in a backup could be too much, depending on the backup's size). Also, if possible pass the generated HTML through a validator (W3C). During development there were many difficulties when links were combined with text formatting (**bold**, *italics*) or multiwidth unicode characters (both around, and _in_ the URL). This could lead to invalid HTML, or to the link tags (`<a>`) being at an offset from the actual link text (`www.example.com`).

The feature is currently behind `--linkify`. If it turns out to work properly, I will probably have that default true in the near future  (to be disabled by `--no-linkify`), but for now it needs to be enabled explicitly.

**Comment by bepaald** [comment]
I bit the bullet and made `--linkify` default. Thanks again!

**Comment by jathri** [comment]
Just tried it and looking good :)
> I think it works the same as Signal's linkify function (it's more or less copied from Android Open Source Project)
Consider this right approach. Thank you.
