### ISSUE TITLE
HTML export: search page not being created, unable to specify directory

### ISSUE THREAD

**Issue by anaxonda** [bepaald/signalbackup-tools#268]
I'm trying to create an export with the --searchpage option, but it is not being created. Here is an example command:

`signalbackup-tools 122724_merge.backup --exporthtml --searchpage --includecalllog --addexportdetails --themeswitching --limittothreads 1`

It successfully exports thread 1, but with no search page (no searchidx.js created). Nor can I specify output directory; if I do I get `[Error]: Failed to parse arguments`. 

I tried specifying directory as relative, full directory, escaping and not escaping it but not working.

Export does seem to work otherwise.

**Comment by bepaald** [comment]
It looks like you are not using the correct options: `--exporthtml` requires the target directory as an argument. Because you are not passing that in, `--searchpage` is used as the target (which also explains why the search page is not generated). Try: `signalbackup-tools 122724_merge.backup --exporthtml [OUTPUTDIRECTORY] --searchpage --includecalllog --addexportdetails --themeswitching --limittothreads 1`.

Let me know if that solves your problem. Thanks!

**Comment by anaxonda** [comment]
That works great. Thanks for your great program and happy holidays!
