### ISSUE TITLE
Successfully merged two backups!

### ISSUE THREAD

**Issue by jayroslyn** [bepaald/signalbackup-tools#29]
First of all, let me just say thank you so much for all of the work you've put into this! I ended up following this simple guide to installing/using the tool: https://gitlab.com/splatops/cntn-signalbackup-tools

Then I was able to merge two databases by running:

`signalbackup-tools signal-2021-03-06-07-59-10.backup "PASSWORD" --importthreads ALL --source signal-2021-03-05-05-29-31.backup --sourcepassword "PASSWORD" --output signal_merged.backup`

I also ended up exporting an XML so I could import old conversations to my default SMS app.

`signalbackup-tools signal-2021-03-06-07-59-10.backup "PASSWORD" --importthreads ALL --source signal-2021-03-05-05-29-31.backup --sourcepassword "PASSWORD" --exportxml signal_merged.xml`

Reference: Issue #27

**Comment by bepaald** [comment]
Since you already referenced #27, I was wondering if you could please check if you are seeing the last issues remaining in that thread: if you had any voice messages in the source-backup, can they still be played (in app) in the merged backup? And if you select _all media_ inside a conversation, do all media show up (from both the old an new backups)?

Very happy it has worked. Thanks a lot for reporting!

**Comment by jayroslyn** [comment]
Unfortunately I don't have any voice messages so I can't check that for you...but all media, from both old and new, shows up in the merged version!

**Comment by bepaald** [comment]
Thanks for reporting back again!
