### ISSUE TITLE
Unable to export backup, suggestions/help !

### ISSUE THREAD

**Issue by ma-phi** [bepaald/signalbackup-tools#36]
- Ran the code on bash and also on windows (using the latest static build given in the repository )
```
$ bash BUILDSCRIPT.sh
./signalbackup-tools --output signal_backup/ signal-YYYY-MM-DD-HH-MM-SS.backup <PASS>
```
- The program read the backup file successfully but when export started it printed this :
```
Exporting backup to 'signal_backup/'
Writing HeaderFrame...
Failed to export backup to 'signal_backup/'
```

**Comment by bepaald** [comment]
Hm... I'm not immediately sure what's happening, but we'll find out!

Just as a first guess... Does the output directory `'signal_backup/'` actually exist? The program outputs to directory if a directory (an _existing_ directory) is passed to the `--output` option. But, if the string passed as output does not exist, it defaults to file-output. This would fail in this case, since the slash ('/') is an illegal filename character. So, if it doesn't exist yet, create the directory first and try again. (Or remove the slash from the command line to export to a file named 'signal_backup').

(I think I'll actually make some changes tomorrow to default to directory-output when the string ends in a slash, that seems a sane default and not to hard to implement)

Let me know if this was helpful or if we have to keep investigating.

**Comment by ma-phi** [comment]
That solved the issue.
Thank-you very much !

- Adding the "default to" code would be a great fail safe for the program, cheers !

**Comment by bepaald** [comment]
Cool, no problem!

> Adding the "default to" code would be a great fail safe for the program, cheers !

Yeah, I actually ended up doing that right after my last message. Hope it works. So thanks for bringing this up, I think it has led to a nice little addition.

Let me know if you encounter more troubles.
