### ISSUE TITLE
Cannot compile, even in new Fedora 

### ISSUE THREAD

**Issue by tclokie** [bepaald/signalbackup-tools#38]
After running `sudo dnf install gcc-g++ openssl-devel sqlite-devel which && sh BUILDSCRIPT.sh`, it builds, then links, then produces the following error

> /usr/bin/ld: /tmp/ccbZb7wo.ltrans12.ltrans.o: in function \`main':
<artificial>:(.text.startup+0xe8f): undefined reference to \`FileDecryptor::strugee(unsigned long)'
collect2: error: ld returned 1 exit status

Any idea why this might be?

For reference, this is on a fresh Fedora VM install (Fedora 34, Workstation Edition), and the software versions from `dnf` include g++ 11.1.1, OpenSSL 1.1.1k, and SQLite 3.34.1.

**Comment by bepaald** [comment]
Ah sorry, I added a file yesterday but forgot to update the buildscript. I'm not at home at the moment, but I will fix it tomorrow. In the meantime, if you want to compile, you could just run `g++ -O3 -std=c++2a - flto=auto */*.cc *.cc -o signalbackup-tools -lcrypto -lsqlite3` (or something similar, if you prefer other build flags) to give the same result.

**Comment by bepaald** [comment]
Should be fixed now. There is also a new buildscript (somewhat experimental), which should take advantage of multicore processors when available (when using bash >= 4.4, which you probably are). You might want to try than one.

Thanks for the report!

**Comment by tclokie** [comment]
Thanks! I was running it in a VM because I thought the build errors might have been due to running Pop OS (based on Ubuntu).

**Comment by tclokie** [comment]
Hi @bepaald, I just wanted to let you know that I attempted a merge of two signal backups (database versions 103 and 111) and when I attempted to restore the merged backup, Signal would just crash upon opening. I don't think this should be filed as an issue, since it's explicitly called an experimental function, but I thought you might like to know.

**Comment by bepaald** [comment]
Thanks for letting me know! I've actually had quite a few success reports for the merge function (the readme is a little outdated I guess). There has been a recent change in signal's database that might have broken something, but I haven't been keeping up with testing lately. I would have assumed if it was a problem my program would fail instead of producing a backup that would crash signal though. 

If you want to, and have time to spend on it, you should feel free to open an issue for this problem.

The first thing to try would be to import the old backup into signal and reexport it so it is at the same db version.Then try the merge again. If it still doesn't work and you decide to open an issue, the first things I'll ask for are the program output and if possible a debug log of signal crashing when trying to restore.

I'll do some of my own testing on the current db format as soon as I have some time (hopefully this weekend).

**Comment by tclokie** [comment]
Will do; I'm just poking around the backups right now and I noticed that running `--listthreads` on the newer backup (db version 111) doesn't actually list the threads, but instead gives this error: `SQL error during sqlite3_prepare_v2(): no such column: thread.recipient_ids`

**Comment by bepaald** [comment]
O wow, ok thanks. I just generated and inspected a new backup and I see a major problem. They seem to have renamed (at least some of) the columns in some of the databases. As long as it's _just_ a rename, it's not too bad, but still a lot of work to fix. So, just wanted to quickly say: don't bother doing anything yet as the program is just broken currently.

But I'm on it. I will have to go through the program to deal with the new column names and then run tests, it'll probably be a few days. I'll let you know.

Thanks again!

**Comment by bepaald** [comment]
Hey! First of all, sorry for the all the noise. I couldn't resist trying to fix the program right away, so I just pushed a possible fix a minute ago.

I have not tested it fully, because I also need to update my test-scripts, but I need to sleep first. Then, the tests will take several hours to run. So if you are feeling brave, you could get the newest version, make sure both your databases are up to date, and try the merge. No guarantees. Otherwise, just wait a little longer, if I have not missed anything I could probably get most of the testing done tomorrow. and I'll let you know.

**Comment by bepaald** [comment]
Well, as far as I can tell from my testing, everything should be working again. I'd say give it a try and report back if you run into trouble. You might even get away with not updating the older database, just make sure to import the old into the new, not the other way around.

**Comment by tclokie** [comment]
Success! It worked!! Thank you @bepaald. I did need to update the older database to the newer version, but after that it worked!

The output included some errors with emoji search stuff (?), but they don't appear to have affected the merge as far as I can tell. They all have the following form:

> Importing statements from source table 'mention'...0 entries...
Importing statements from source table 'payments'...0 entries...
Importing statements from source table 'chat_colors'...0 entries...
Importing statements from source table 'emoji_search_data'...2 entries...
SQL error after sqlite3_step(): UNIQUE constraint failed: emoji_search_data.id
SQL error after sqlite3_step(): UNIQUE constraint failed: emoji_search_data.id
Importing statements from source table 'emoji_search_idx'...0 entries...
Importing statements from source table 'emoji_search_content'...0 entries...
Importing statements from source table 'emoji_search_docsize'...0 entries...
Importing statements from source table 'emoji_search_config'...1 entries...
SQL error after sqlite3_step(): UNIQUE constraint failed: emoji_search_config.k
Importing statements from source table 'sender_keys'...0 entries...

Thanks again!!!

**Comment by bepaald** [comment]
Cool, happy to help.

Yeah the two errors don't look very nice but the solution (which I'll push soon) is to just clear those tables before importing (they are explicitly ignored on import by the android app anyway). So the end result will be identical.

Maybe if you have time you could check something for me. Although most mergers seem work ok, I have one long open issue (#27) where after merge some (all?) audio messages fail to play. They can still be saved and played with an external application, but playing inside the app fails. Also, when inside a conversation, going to the menu and selecting 'all media' seems to either leave out some images or show them in an incorrect order (just in the overview, in the conversation they appear fine).

Maybe these issues have been fixed, I have never been able to reproduce them in the first place, so I'm not sure, but maybe you could try to see if you easily notice these problems. Thanks!

**Comment by tclokie** [comment]
Audio messages are working fine on my device, both in the conversation and the "All Media" section. The order also seems to be right, as far as I can tell, but I can't be sure because I don't remember the exact order off the top of my head. No issues here!

Only thing of note I see is that when I scroll back pretty far and Signal has to load some old messages from months ago, it takes a pretty darn long time to load... but it does load after a minute or so!
