### ISSUE TITLE
-- dumpmedia enumerates duplicate filenames in the file extention rather than the file name and doens't count up

### ISSUE THREAD

**Issue by Meteor0id** [bepaald/signalbackup-tools#49]
image.jpg
image.jpg(2)
image.jpg(2)(2)

this should have been

image.jpg
image(2).jpg
image(3).jpg

**Comment by Meteor0id** [comment]
Just know that at some point the file name becomes too long, causing errors for any next files with the same name. therefore counting up is important.

Maybe the position issue can be solved by having a hard-coded list of common mime types and recognizing for example .tar.gz as a single extension.

**Comment by bepaald** [comment]
Yes, I'm thinking of going this route. It's not a nice solution, and not future-proof. But since most files in the database will not have a filename at all, I had to add the extension from the mime type, so I'm already including a list of known mime types. Might as well use it for this purpose as well.

I will get on it when I have time (but it might go slowly, I'm busy at the moment).

Thanks!

**Comment by stefan-schiffer** [comment]
see #65 for a batch file that increments a counter for files with duplicate names and renames them.

**Comment by bepaald** [comment]
I finally got around to this. I went with the quick solution, so it will run into the problems I mentioned in my earlier comment (https://github.com/bepaald/signalbackup-tools/issues/49#issuecomment-963006344). But after thinking about it, no solution for this problem is perfect. Even when doing it in two passes, there can be situations without a clear best solution.

At least, duplicate filenames will now have a counter that counts up properly, and the extension will not be mangled.

I'm closing this for now, but please feel free to comment or even open up a new issue if you see any problems. Thanks!
