### ISSUE TITLE
not all command line arguments are documented - no single "man page" reference?

### ISSUE THREAD

**Issue by tomperrine** [bepaald/signalbackup-tools#51]
Thanks for making this! I have messages in Signal going back to 2011, and wanted to make sure I had a safe non-signal backup. (I imported all my old SMS into Signal when I first started using it, so 11 years of messages, and yes, I am a packrat!)

I noticed that there's not a lot of documentation for the various command line options. Or am I looking in the wrong place? Is there a single reference?

If not, would you be able to answer some questions as I try to make one?

**Comment by bepaald** [comment]
Hi! Glad to hear the program is useful to you.

It's true documentation is somewhat lacking. I feel most of the core functionality is mentioned in the [README](https://github.com/bepaald/signalbackup-tools#readme), but that might not be the best place. At least a few useful options (`--no-showprogress` comes to mind) are indeed missing. Then there are a bunch of options, which I don't expect to ever be used or were written specifically for one person and their specific problem. These I feel needn't be documented at all, or at most just mentioned in the readme with a reference to the github issue where they were discussed.

I have been having the strong urge to try writing at least a `--help` function, as most normal programs have, to list all options, but I have not started yet. Some options may not really be suited to that format as they only make sense when combined with other options (some optional, some even required). But I think I can make it work somehow. Just not sure when I'll find the time.

If you feel you want to write some documentation (a man page, a help function, a website, what were you considering?), please be my guest. It would be appreciated. Naturally I'll answer any questions you might have.

**Comment by tomperrine** [comment]
I'm writing a man-page style doc, for now. I'm using the argument processor function and the README as the first source material.

I've identified the 67 command line options, and found  reference to 28 of them in the README. I'll dive into the code to see what's up with the rest of them. I see the "specials" - I think I'll list them in their own section. Adding links to the github issue is a great idea, I hadn't thought of that.

I decided to use the manpage format, since it is a Linux program. And man page .groff formats can be used to generate HTML and Markdown via pandoc, etc.

My C++ is rusty, so this will give me a chance for a refresher :-). The last time I wrote a man page using roff format from scratch was a looong time ago. Probably for SunOS!

**Comment by bepaald** [comment]
Well, good luck. I'm curious to see what you end up with. I have actually made a little start at writing a `--help` function, and it is much more difficult than I had thought. There are actually quite a few options where I can't really decide whether they should be documented at all. Also I have the urge to group the options in some logical way, but that too is not a clear and simple task. But I'm sure I'll get something together soon.

Good luck to you. I have zero experience with groff, it will be interesting to see the result (but, of course, do not feel obligated).

**Comment by tomperrine** [comment]
Now I remember why I hate troff so much!  Abandoned that idea and have written the first pass of a man page in Markdown.

PR #55 for review - just to see if I'm on the right track before I dove into the code itself.

**Comment by bepaald** [comment]
Hi Tom,

Sorry for the long wait, it's been a bit crazy lately. But I have been coding a little as well and of course I looked at your pull request. Thank you so much for your hard work with this.

As you mentioned yourself, there are quite a few flaws in that first attempt, maybe even too many to list here individually, this is largely due to the mess I've made of the arguments. I'll probably have to think about cleaning it up at some point, but I don't see a obvious way to right now. I'll try to give some general comments and answer some of the questions you wrote in the draft.

Generally, there are two categories of options: some options tell the program to perform some action, others modify the behavior of said actions. For example: `--croptothreads` makes the program crop a backup to certain threads, while `--limittothreads` is a modifier for `--deleteattachments`, causing it to only work on certain threads. Most modifiers are optional, but some are required (if one calls the `--importthreads` option, a `--source` database from which to import the threads _must_ also be passed).

The reason some options have an undocumented '--no...' variant (`--no-listthreads`) is simply because I'm actually auto-generating the argument parser (hence it's illegibility ;) ). In other programs I've written, it sometimes makes sense to have a config file with default options set. In order to overwrite the defaults from a config file, all options that are just boolean switches (not taking any parameters) automatically get a corresponding '--no-...' option. For this program the config file doesn't make much sense I think, so I disabled it, but it leaves the (unused) '--no-...' options. Though if your backspace key is broken and you accidentally write `signalbackup-tools --verbose`, you can follow that with `--no-verbose` to undo it :)

I've just pushed an update that adds a (first attempt at a) help function to the program. I think that will probably also provide some insight into the available options. Modifiers are explicitly mentioned as such. I believe I listed all even slightly relevant options, though I think I finally also left a few out (that I knew or strongly suspected were broken). I'd say take a look: `singalbackup-tools --help`, and let me know what you think.

If I'm completely honest, if I had to write a man page myself, I probably wouldn't bother now that both the `--help` and the README.md exist (though both could probably be improved). Both writing it in the first place and keeping it up-to-date seem like daunting tasks to me at the moment (but I admit I'm a bit overworked). As soon as I find some time to adjust my tooling, the help-output will be auto-generated together with the Arg-class (from the same input), so keeping it updated will hopefully be relatively simple. Having said that, if you feel the man page adds benefit and are still willing to write it, I'll happily accept.
