### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by Terge3141** [bepaald/signalbackup-tools#53]
Dear bepaald,
thank you so much for providing this great tool. I created a Makefile for this project. Would you be interested? Then I'll setup a pull request?

Best regards,

Michael

**Comment by bepaald** [comment]
Hi Michael,

Thank you so much for your interest in this project.

There has been discussion about a Makefile before. And I have written various ones myself, first very simple ones that would require little to no maintenance*, then more and more complex ones to deal with people's demands for supporting different compilers and older version of compilers and using cryptopp instead of openssl. These versions were really not good and should have been generated with autoconf and such tools. But, I was (and am) not really willing to learn all theses tools. I do now feel a simple, low-maintenance Makefile, just for a default compile, would be something nice to have.

Also, I am really not too familiar with writing Makefiles, so maybe mine were just bad because I didn't know what I was doing. I'd love to at least see your version and hear your feedback on what I came up with.

\* This one specifically, both normal make and `make CXX=clang++` work at least, and I actually think most exotic builds can be made to work by overriding CXXFLAGS and such in a similar way:
```
SRC := $(wildcard *.cc */*.cc)
OBJECTS = $(join $(addsuffix o/,$(dir $(SRC))),$(notdir $(SRC:.cc=.o)))

#$(info SRC is $(SRC))
#$(info OBJECTS is $(OBJECTS))

# default values
CXX = g++
CXXFLAGS += -Wall -Wextra -Wshadow -Wold-style-cast -Woverloaded-virtual -pedantic -O3 -flto
CXXVER = -std=c++20
TARGET_ARCH = -march=native
LDLIBS = -lcrypto -lsqlite3
LDFLAGS += -Wall -Wextra -Wl,-z,now -Wl,--as-needed -s -flto=auto
BIN = signalbackup-tools

# link
signalbackup-tools: $(OBJECTS)
	$(CXX) $(LDFLAGS) $(TARGET_ARCH) $^ $(LDLIBS) -o $(BIN)

# compile
$(OBJECTS):
	@mkdir -p $(dir $@)
	$(CXX) -c -o $@ $(CXXFLAGS) $(CXXVER) $(TARGET_ARCH)  $(subst .o,.cc,$(subst o/,,$@))

clean:
	@rm -f o/*.o */o/*.o signalbackup-tools
```

Thanks!

**Comment by Terge3141** [comment]
Thanks a lot. That was really helpful for my java implementation https://github.com/Terge3141/signalbackupreader

**Comment by bepaald** [comment]
Well, I don't think I completely know what happened in this issue, but... Your welcome? Happy to have helped.
