### ISSUE TITLE
Successful Merge Feedback

### ISSUE THREAD

**Issue by marleygf** [bepaald/signalbackup-tools#54]
Hi,

Just jumping in to say I had to move to a new number on android (same device). All done today so same DB version.

Steps taken:

- Created backup on old account
- Deleted old account
- Create new account after signal reinstall
- Created new backup on new blank account
- Pull both backups from device and merge using example command
- Delete signal on android again
- Restore from new merged backup file

Seamless and flawless.  A few `.Warning: attachment data not found ` warnings, likely from actions on my own end though, lots of convo history so unlikely to find backups in question but will edit later if I see anything suspicious.

All media (voice/photos/video/stickers) work great, only missing elements were custom convo backgrounds. Not sure if this is expected, but also extremely minor "flaw".

Thank you so much, this was a lifesaver!

**Comment by bepaald** [comment]
Hey thanks! Glad it worked well for you. I believe I've gotten so many reports of success, I should probably update the readme to reflect that (though updates to signal always potentially break functionality).

The warnings can indeed be ignored. I have some theory which messages this happens with, but I have too few backups exhibiting this 'problem' to really prove it. As far as I can tell, it happens when attachments are quoted, and the original quoted attachment is either deleted, or not an image or video file (= not requiring a thumbnail). At least this is the case in all the cases I can investigate. Either way, manual inspection always shows the attachment data is not just not found, but actually not present in the backup.

As far as I know custom convo backgrounds are not backed up by the app either, so that seems right, but I will check to make sure.

Thanks again for your detailed report!
