### ISSUE TITLE
Add Docker Support

### ISSUE THREAD

**Issue by davidjmeier** [bepaald/signalbackup-tools#6]
Since there are specific requirements for this tool to be compiled adding Docker support will alleviate being able to run everywhere.

I've already done this so feel free to link to my repo:
https://gitlab.com/splatops/cntn-signalbackup-tools

Or if you'd like feel free to add this directly to your project.  Thank you for the tool!

**Comment by bepaald** [comment]
I hadn't seen this message before I replied to your previous one. Please disregard the request for a PR, I'll link to your repo in my README.
Thanks again!


    On Monday, November 18, 2019, 4:44:17 PM GMT+1, David J. Meier <notifications@github.com> wrote:  
 
 
Since there are specific requirements for this tool to be compiled adding Docker support will alleviate being able to run everywhere.

I've already done this so feel free to link to my repo:
https://gitlab.com/splatops/cntn-signalbackup-tools

Or if you'd like feel free to add this directly to your project. Thank you for the tool!

**Comment by davidjmeier** [comment]
Awesome, thanks for the great tool!
