### ISSUE TITLE
wrong extensions for multiple jpg-files sent with a single message

### ISSUE THREAD

**Issue by stefan-schiffer** [bepaald/signalbackup-tools#65]
dumping media with option --dumpmedia  creates wrong extensions for multiple jpg-files sent with a single message. example

signal-2022-02-24-134226.jpeg(2)(2)(2)(2)(2) 

is the name of a jpg-file that belongs to a message with 6 pictures attached. 
 
![image](https://user-images.githubusercontent.com/4481320/162616910-896bdcb8-6e2a-4de3-8a77-a830b8b3d97a.png)

**Comment by bepaald** [comment]
Yeah, this was a quick and dirty solution to an otherwise somewhat difficult challenge. See #49 for more comments.

I never really cared much, since a wrong extension seems a non-problem (and the files in the backup actually more often than not have no extension at all, I'm adding that '.jpeg' at the end), but I suppose on OS's that rely on the extension (ie Windows) this is an issue.

I'll get on it as soon as I have time, hopefully tomorrow. Not yet sure what the best solution is going to be though... 

I'll leave this open until I've fixed it to remind myself to do something with it.

Thanks for your report.

**Comment by stefan-schiffer** [comment]
Thanks for your quick response. The fix is not urgent because I have written a batch file that starts with a given directory and recursively renames all media files containing "(" in the extension, so 

signal-2022-02-24-134226.jpeg(2)(2)(2)(2)(2) will become
signal-2022-02-24-134226_6.jpeg

![image](https://user-images.githubusercontent.com/4481320/162635449-9f7805a4-5496-4452-94a3-77e0e46dd67e.png)

Here's the quick and dirty code for media files dumped to directory _media_.

```
@echo off

set dir=media
setlocal enabledelayedexpansion

cd %dir%
for /d /r %%D in (".") do (
	pushd %CD%
	cd %%D
	for %%F in (*.*) do (
		set n=%%~nF
		set x=%%~xF
		set y=!x:(= !
		set i=0
		for %%X in (!y!) do set /a i+=1
		set z=""
		for /f "tokens=1" %%X in ("!y!") do set z=%%X
		if !i! gtr 1 (
			set new="!n!_!i!!z!"
			rename "%%F" !new! 
		)

	)
	popd
)
```

**Comment by bepaald** [comment]
Ok, this should be fixed. I'm closing this for now, but please comment or even open a new issue if you still have problems.
