### ISSUE TITLE
Fixing backup fails

### ISSUE THREAD

**Issue by crissimaster** [bepaald/signalbackup-tools#8]
I have a broken backup and want to fix it but the program stops with some error.

As proposed I'll attach a full output of the program.
[signalbackup-tools_log_20200503.log](https://github.com/bepaald/signalbackup-tools/files/4571396/signalbackup-tools_log_20200503.log)

**Comment by bepaald** [comment]
Thanks! That's quite a long log! I've just quickly looked through it, and it is obvious the backup file is in a really bad state. It fails early on in a very small frame, which is unlikely (in fact I've never seen this actually happen).

Any errors in a backup file will usually propagate causing more errors on the frames following the first bad one. My program tries to recover from this, and up until this case it has succeeded unless there were actually no good frames in the file at all. So, either my program needs improvement or your backup file is beyond repair.

I will try to create a broken backup here that produces the same errors as yours to try and work on it. But I'll have to think hard about it and look at your log a bit better tomorrow.

I assume the original phone and signal installation which created this backup are no longer available? That is, you can not simply create a new backup?

**Comment by crissimaster** [comment]
> Thanks! That's quite a long log! I've just quickly looked through it, and it is obvious the backup file is in a really bad state. It fails early on in a very small frame, which is unlikely (in fact I've never seen this actually happen).
Interesting.
 
> Any errors in a backup file will usually propagate causing more errors on the frames following the first bad one. My program tries to recover from this, and up until this case it has succeeded unless there were actually no good frames in the file at all. So, either my program needs improvement or your backup file is beyond repair.
Hm...

> I will try to create a broken backup here that produces the same errors as yours to try and work on it. But I'll have to think hard about it and look at your log a bit better tomorrow.
Let me know if you need more info.

> I assume the original phone and signal installation which created this backup are no longer available? That is, you can not simply create a new backup?
I still have the old phone (Xiaomi Redmi Note 4) and access to Signal and its messages. I tried several times to disable backup, enable backupping again (getting also new passphrase). But it seem to fail always.
Signal on the old phone is 4.58.5, on the new phone (Xiaomi Redmi Note 8 Pro) is 4.59.6.
The backup size is not big (~225MB).

**Comment by bepaald** [comment]
Just wanted to give a quick update. It's not looking too good I think. Let me explain a little about the backup file:

The backup file is divided into 'frames' each of which is
- 4 bytes representing the size of the rest of the frame (S)
- S - 10 bytes being the encrypted data
- 10 bytes: a hash of the previous S - 10 bytes, used as an integrity check (this is the MAC)

That's it, you read 4 bytes, then S-10 bytes, then you hash those and check the hash with the next 10 bytes and repeat. After that, of course, there is a lot more work to be done (actually decrypting the data and interpreting the decrypted bytes), but that basically never fails. What happens in your file is the hash check fails, indicating data corruption (you can see it in my program, but also in the signal debug log you posted on the signal issue tracker which ends with '_java.io.IOException: Bad MAC_').

From the output you posted I think I'm fairly certain the corruption starts in the encrypted data, and extends at least into the next frame's size-byte. You can see this from your output from the fact that the first frame with the bad MAC (frame 131) is partially there but is incomplete, then the hash is wrong, and then the size of the next frame is obviously incorrect ('_Failed to read next frame (2798922099 bytes at filepos 32816)_', which corresponds to a frame of 2.6GB which is impossibly large). After which my program starts bruteforcing: meaning, it will just interpret every next byte offset as the start of a frame and tries to verify the hash to get back in sync with the backup file.

Now I've artificially created a backup with all the types of corruption that could explain the output you posted in your first post (that I could think of), but whatever I do, my program seems to always find the first non-corrupted, valid frame and continues decrypting the database. With your file however it does not seem to find any proper frame anywhere in the rest of the file. So, my current assumption is that all the bytes in your backup file after that first error are corrupt. I will continue to think about alternatives and test those, but right now, I don't think it looks good.

> I still have the old phone (Xiaomi Redmi Note 4) and access to Signal and its messages. I tried several times to disable backup, enable backupping again (getting also new passphrase). But it seem to fail always.

This is very interesting. Some ways in which the backup can become corrupted is if the phone's memory is faulty or the file gets corrupted while transferring it of the phone (might seem unlikely, but multiple people that have come to me have had this problem). But since you still have your old phone, both of these things can be checked, and it can make it more or less likely there is a bug in signal. So, if you have some time and want to try, please:
- Create a new backup on the phone (no need to enable and disable, you can just tap the 'create backup' option
- Tap the 'create backup' again. This makes it so that you have two identical backups on the device at the same time (so they can't occupy the same parts of your phone's storage).
- With both backups still on the phone, create a hash of the files. Any hash will do, but if you have no favorite method or app, I usually use this app to generate an MD5 sum: https://play.google.com/store/apps/details?id=leonidpeter.hashstamp
- Now transfer both backup files to you computer, and check the hash, if the hashes differ the file has corrupted during transfer.
- Then run my program on each backup and see if the errors are the same in both backups (especially same first frame number with bad mac)

This should tell us a with a bit more certainty wether it is Signal that is writing bad backups or the corruption happens elsewhere.

**Comment by crissimaster** [comment]
Hello,

> Just wanted to give a quick update. It's not looking too good I think. Let
> me explain a little about the backup file:
> 
> The backup file is divided into 'frames' each of which is
> - 4 bytes representing the size of the rest of the frame (S)
> - S - 10 bytes being the encrypted data
> - 10 bytes: a hash of the previous S - 10 bytes, used as an integrity check
> (this is the MAC)
This makes sense.

> This is very interesting. Some ways in which the backup can become corrupted
> is if the phone's memory is faulty or the file gets corrupted while
> transferring it of the phone (might seem unlikely, but multiple people that
> have come to me have had this problem). But since you still have your old
> phone, both of these things can be checked, and it can make it more or less
> likely there is a bug in signal.
Yes, thats right. Yesterday I had time to look on it and found some really 
interesting facts:

The md5 sum differs as I transferred the files from old phone to PC, and also 
from PC to new phone!
I used kde-connect (1.4-0ubuntu5) to transfer the files. This worked without 
any problems in the past.

Now, I used an ftp server to transfer the files on both mobiles and now the md5 
sum on the new mobile matches to the md5 sum on the old mobile.

Then, I tried to import the backup and it worked without any problems.

So, the good news are that it seem there is no bug in signal regarding backup 
export (at least for me).

I filed a bug on kde for kdeconnect, to let check the devs whats going wrong 
there:
https://bugs.kde.org/show_bug.cgi?id=421176


A big thank you to you! You reminded me that verify the integrity on these 
days is still a thing we should consider in this days ;)


Kind regards

Christoph
--

**Comment by bepaald** [comment]
Excellent! I am happy that there's no bug in Signal, more happy there is no bug in my program, and _even more_ happy that you were able to successfully restore your backup!

Glad to have been able to help, feel free to contact me if you ever have another backup related problem.
