### ISSUE TITLE
todo: import from desktop without an android backup file

### ISSUE THREAD

**Issue by Meteor0id** [bepaald/signalbackup-tools#89]
Was wondering if it will ever be possible to use this tool to export signal desktop without an android backup file, for example when chats and contacts on android have been (partially) erased or the android device was lost.

As of currently the tool can not identify contacts whos data is not also on android

**Comment by bepaald** [comment]
I'm not sure this is possible. I'll leave this open for now, maybe I'll get around to testing this in the sometime in the future. I think it's a pretty rare case where it is not possible to get the contact back in the database (even without starting a conversation).

**Comment by meiser79** [comment]
This is exactly what I currently need. I have a Signal Desktop database which I'd like to import into a freshly installed phone.

**Comment by mightyCelu** [comment]
I'm also currently in a situation where I'd benefit from this feature. 
Based on this I'm bit stalled, since I'm not sure what will happen if I proceed with the phone setup on the new installation.
Will this "invalidate" the running desktop session, leaving me without access to the existing messages, or will I "join" it again, just without the history of each chat?
I'm hoping for the latter case, with the potential of importing the history at some later point, but would love to have some indication that proceeding will, in fact, be non-destructive.

Any insights into this would be greatly appreciated!

**Comment by bepaald** [comment]
Is it not possible to get the contacts back in your phone?

I have had a few more messages exchanged with meiser79 here: https://github.com/bepaald/signalbackup-tools/issues/57#issuecomment-1741840003 (and the next few messages). They seemed to have solved their issue by re-linking.

_***WARNING*** Do not take my word for it: I have no first hand knowledge and do not want to be responsible for your data loss. Always make backups of important data._
As far as I know, linking a phone _with the same phone number_ you will keep your history in Signal Desktop, linking a phone with a new number will erase everything.

**Comment by mightyCelu** [comment]
Thanks a bunch! As you suggested, setting Signal up on the phone allowed me to re-link my PC-session, after which both worked, with the old messages being available on the PC session. Of course I did a backup beforehand :)

From here I'll try and see whether I can import the Desktop messages into a backup generated by the phone to have them available there, but for now this is already very usable. Small caveat for others: Make sure to re-link to the desktop session shortly after setting up the phone, as that will break the link and messages received in the mean time will not be present on the PC.

**Comment by bobatsar** [comment]
I just also wanted to confirm that this was working for me.

1. Backup of desktop config
2. Reconnect new phone with desktop -> Contacts are synced
3. Create empty backup archive on phone
4. Import desktop archive into phone backup
5. Uninstall and reinstall signal on phone
6. Import modified backup
7. Reconnect desktop again with phone.

@bepaald thanks for this nice tool. Without it my whole message history would have been gone on the phone.

FYI: current libsqlite3 on Ubuntu 23.10 was working nice. No PPA was required.

**Comment by bepaald** [comment]
That's good to hear! Thanks for the feedback!

---

As for the original issue: I've given this some thought and realistically it is not going to happen. Creating a new backup out of thin air already has all the same issues as importing into an existing backup without the same contacts (that alone is already not possible), but brings a lot more as well. The first frame to generate would be the 'databaseversionframe', in which I would have to pick a database version to target. In practice this would mean having to keep track of, and implement Signal's constantly changing SQL schema.

I do not believe this feature is entirely possible, but even just trying to implement it to see if it works would require an unfeasible amount of effort. So just to clean up a little, I'm going to close this issue as it will just stat open without any progress indefinitely otherwise.
