### ISSUE TITLE
BAD MAC Error with Flatpak Directory

### ISSUE THREAD

**Issue by Neon-44** [bepaald/signalbackup-tools#97]
when i try to use Signalbackup-tools and pass the flatpak directory to --importfromdesktop, i get a BAD MAC Error and it fails to open the Database.

i assume it is because i use a flatpak, although it could also be that i imported my messages history from an earlier Signal Desktop client. but i can use the app perfectly fine.

is there any way i can fix this or just tough luck?

p.S. thanks for this amazing tool, it's just awesome!
thanks for providing this when Signal wouldn't want to.

**Comment by bepaald** [comment]
Ok, strange. Is that flatpak of Signal Desktop up-to-date? Signal Desktop used to use sqlcipher version 3, but has moved to version 4 (though it was quite a while ago, almost 3 years I think). Is there any chance this is still a version 3 database? This would cause a bad mac error.

This program does actually support reading version 3 databases, but I'd need to add some code to actually select it.

>i assume it is because i use a flatpak, although it could also be that i imported my messages history from an earlier Signal Desktop client. but i can use the app perfectly fine.

What exactly do you mean by this? I did not think such functionality existed.

**Comment by Neon-44** [comment]
>Ok, strange. Is that flatpak of Signal Desktop up-to-date?

yes, all my apps are up-to-date. i think signal Desktop is 6.6.0
at least it got the new stories, so it can't be a completely stuck-in-time package.

>What exactly do you mean by this? I did not think such functionality existed.

i can't quite remember anymore, but i think it was when i was back on windows, i just grabbed the entire Signal Data Folder, copied it onto a USB Stick, plugged it into my Laptop and "synced" the whole Conversation history like this lol

but i guess if it works for Signal Desktop, it should also work for signalbackup-tools :/

**Comment by bepaald** [comment]
Ok, I just added the option to set the sqlcipher version, so just to test, add `--desktopdbversion 3` to your command line and see if that changes anything. If you still get a bad mac, it should now also print out a page number. I'd be interested in that (mostly if it's 1 or higher).

Also, be aware that while `importfromdesktop` has been working for a number of people, it could also still miss some data (or even fail completely) on very old Desktop databases (which you might have). This is mostly because I don't have any very old databases myself and the database format seems to have been very different in the past.

**Comment by bepaald** [comment]
>i was unable to compile the new tool, but i didn't want to stand here empty-handed when you did so much for me, so i decided to retry the nixpkg backup-tools with my native NixPkg Signal Install (Signal 5.63.1).

Ah, I take it you're on a Mac? Compiling seems to be a bit complicated indeed. I don't think the nixpkg is completely up-to-date, but it's certainly not old, so it shouldn't matter in this case.

>i wiped all data, paired it again, sent a message to myself aand.. got the same error again.

Well, I guess it could not be an old sqlcipher version then....

>is it possible that the Database isn't the Problem?
the calculated hex ends with a lot of zeros, if that helps you debug it

Yeah, of course, it could be a bug in my code, though I'd have guessed a bug in this part of the code would have shown itself much sooner.

Usually when I see zeros in the MAC (always on the Android backup file), it meant the data was corrupted (this program started out as a way of retrieving what it could from corrupted backups), but that seems hard to believe in this case, as you can still use the app. Are the `MAC in file` and `Calculated` the same length at least? Does the non-zero part match?

I'm afraid I'm not sure what to do at this point. I usually debug these things by making changes to the program and having the user rerun and report back, but you can't easily get up-to-date versions. It's not the quickest way of debugging, but it's all I can do without having access to the problematic backup files myself.

Two things I can think of to do (maybe long shots, and maybe too much trouble for you):
- If you have access to any other computer, running Linux or Windows, copy the 'Signal' folder over, and try it on there.
- Try to open the database with an other program that uses sqlcipher. A quick search gave me these instructions for mac: https://danielbeadle.net/post/2020-05-19-signal-desktop-database/ which may work. Also note step 7 where the sqlcipher version is set. If it opens ok, try running a few queries like `SELECT body FROM messages;` and `pragma integrity_check;`.

Sorry to be of little help on this one. I'll get back to you if I think of anything else. I might try firing up my macOS VM, but that comes with it's own issues...

**Comment by Neon-44** [comment]
>Ah, I take it you're on a Mac? Compiling seems to be a bit complicated indeed. I don't think the nixpkg is completely up-to-date, but it's certainly not old, so it shouldn't matter in this case.

ah, no, i'm actually using NixOS on a HP Envy. 
i've just never had any "actual proper" Linux experience, so doing trivial things on NixOS is even harder for me since i don't know how to it on a "normal" system as well.

i also tried compiling it with a Fedora Distrobox, but that didn't work either :/

> Are the MAC in file and Calculated the same length at least?

yes, they seem to be

>Does the non-zero part match?

nope, not at all

>Sorry to be of little help on this one. I'll get back to you if I think of anything else.

i don't feel that way at all!
you answered me so fast and tried to help me so much!
i am really grateful for everything you've done for me, considering this is a free-time-project of yours!

>I might try firing up my macOS VM, but that comes with it's own issues...

haha, that probably wouldn't help much, considering that i am using NixOS and not MacOS, but thanks :))

i just received your second comment, i will quickly try it and make a new comment, brb :)

**Comment by Neon-44** [comment]
> > i wiped all data, paired it again, sent a message to myself aand.. got the same error again.
> 
> I did just find this: https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#desktop_restore which has some remarks about copying the data folder. But that shouldn't be a problem on the fresh install. So, I was just thinking, do you specify the Signal directory each time you tried this (so that you're sure it's picking up the new installation)? There is still a BAD MAC, but is it at least a _different_ mac?

if i don't specify the directory, it doesn't even find the config.json:
```
Failed to open input: /config.json
Error : Failed to open database
```

**Comment by bepaald** [comment]
Ok, well running NixOS in a VM should be much easier. I'll see what I can do, maybe I can help you compile and run the latest version of this program, or install sqlitebrowser and open the Signal Desktop database with that.

Not sure if I'll have time today, maybe it'll be tomorrow...

**Comment by Neon-44** [comment]
alright, take your time. thanks to the "merge" feature i shouldn't be in too much of a hurry. 
thank you for your help, i really appreciate it :)

**Comment by bepaald** [comment]
When I install signalbackup-tools with `nix-env -iA nixos.signalbackup-tools`, it installs a pre-built binary from some server that is hopelessly outdated: 20221025. What version are you running (it's always the first line of the output)? I can not figure out how to tell nix-env to build from source...

Though I have no idea what I changed since then to the database decoder, I can reproduce your issue with this version. Just to give you an idea: there have been two new releases _just today_, and currently most changes are made to the desktop import functionality. It is very important to always run the latest version.

Fortunately, I did manage to build the current version from source. Instructions:
- open a terminal (konsole)
- install the requirements: `nix-env -iA gcc git openssl sqlite`
- download this program: `git clone https://github.com/bepaald/signalbackup-tools`
- `cd signalbackup-tools`
- start a nix-shell with the correct environment: `nix-shell -p gcc openssl sqlite`
- build it by running `bash BUILDSCRIPT_MULTIPROC.bash44`
- `exit`, to exit the nix-shell

With the current version, the error is gone (for me, at least). Make sure to run the newly built version: be in the directory and prepend the command with `./`, so `./signalbackup-tools ....` (calling just `signalbackup-tools` will use the globally installed, outdated version (which you might as well remove)).

Some more remarks:
- Building could take a little while, depending on your computer (my main machine does it in 13 seconds, but the laptop that's running NixOS in a VM takes 4 minutes!
- When new changes are made (which is often), you can change to the signalbackup-tools directory and run `git pull` to update the source files, after this you need to recompile (start the nix-shell and run the script). If the changes are small enough this will go a lot faster, since only the updated files are recompiled. If this causes errors, the changes were too big and you need to delete all the '.o' files before building again (or just delete the entire directory and start the above instructions from `git clone`).
- If you need to supply the Signal dir to `--importfromdesktop` (for the signal-desktop nixpkg, it is not needed since it's in the default location), you now need to supply two directories instead of just one like you were probably doing now. So: `--importfromdesktop [dir1] [dir2]`. In practice `dir1` and `dir2` will probably always be the same. This is because under Windows the `config.json` and the `sql/database` used to exist in separate directories. This is not the case anymore, so I will probably change this again in the future.

Also please note that what I said before is still a thing:
>Also, be aware that while importfromdesktop has been working for a number of people, it could also still miss some data (or even fail completely) on very old Desktop databases (which you might have). This is mostly because I don't have any very old databases myself and the database format seems to have been very different in the past.

The import function is very new and I'm still working out the issues, especially for old databases (that is, databases that have existed for a long time, the earlier messages may be formatted in ways that I (and this program) don't know about).

Let me know how it goes...

**Comment by Neon-44** [comment]
alright, that worked 🥳 

thanks so much for your help, i really appreciate it!
I sent you a small token of appreciation over Ko-Fi

i found the error with the nixpkg btw, it seems that nix-env and nix-shell both use the stable (22.11) repo, where the new versions of signalbackup-tools hasn't been backported to. if some nix-wizard finds out how to use the unstable channel, you should be able use signalbackup-tools just fine (probably)

just a few notes for people stumbling upon this on a later point:
1. the outdated version of signal-backup-tools only takes one path/argument for --importfromdesktop, the newly compiled one takes two. make sure to adjust it accordingly or you're going to spend a few minutes debugging. at least that's what happened to me.
2. for some reason i re-received the notifications for all the messages i received in the last few days, so that can happen.
other than that everything seems to work though.

**Comment by bepaald** [comment]
> alright, that worked partying_face
> 
> thanks so much for your help, i really appreciate it! I sent you a small token of appreciation over Ko-Fi

Thanks! That's very kind of you. And I didn't even have to write any code for this issue! :-)

> 
> i found the error with the nixpkg btw, it seems that nix-env and nix-shell both use the stable (22.11) repo, where the new versions of signalbackup-tools hasn't been backported to. if some nix-wizard finds out how to use the unstable channel, you should be able use signalbackup-tools just fine (probably)
> 
> just a few notes for people stumbling upon this on a later point:
> 
>     1. the outdated version of signal-backup-tools only takes one path/argument for --importfromdesktop, the newly compiled one takes two. make sure to adjust it accordingly or you're going to spend a few minutes debugging. at least that's what happened to me.

Yeah, I noted that in the last remark of my previous post (no worries, it was a lot of text), but for people stumbling upon this later: as long as your Signal Desktop (/Beta) keeps its files in a default location, `--importfromdesktop` will not need any arguments at all. Only when the paths are non-default (like in a flatpak container) will you need to supply them. Also, I will probably change the number of arguments back to 1 sometime in the future as the two paths are always the same these days. When in doubt, try `signalbackup-tools --help`.

> 
>     2. for some reason i re-received the notifications for all the messages i received in the last few days, so that can happen.
>        other than that everything seems to work though.

I'm so glad the actual import went smoothly at least, that's very good to hear.

Thanks!
